/**
 * Unified data layer for paper state — Convex-first with graceful fallback
 * to the static papers.ts + live-status.ts files.
 *
 * Phase 4 of the data-model rebuild (project-context/DATA_MODEL_ARCHITECTURE.md).
 *
 * Behavior:
 *   - If NEXT_PUBLIC_CONVEX_URL is set + Convex reachable → fetch live
 *     paper state from convex/papers.ts listAllPaperStates query.
 *   - Otherwise → merge static papers.ts + live-status.ts as before.
 *
 * Returns the SAME shape regardless of source, so callers don't have
 * to branch. The Convex source becomes canonical once Phase 1.5
 * (npx convex dev + seed migration) lands.
 *
 * Server-side only — uses ConvexHttpClient (not React useQuery), so safe
 * for use in Next.js server components without converting to client.
 */
import { papers as staticPapers, type Paper } from "@/data/papers";
import { liveStatus } from "@/data/live-status";

export type LivePaperState = {
  slug: string;
  number: string;
  shortTitle: string;
  status: string;
  currentVersion: string | null;
  lastUpdated: string | null;
  readinessComputed: number;
  openBlockers: number;
  openMajors: number;
  openMinors: number;
  openCaveats: number;
  houstonSignOff: string | null;
  sitePdfPath: string | null;
  // Canonical 4–6 focus bullets per paper (used by the detail page so it
  // can stop hardcoding them). Convex source-of-truth — fallback is empty.
  focusAreas: string[];
  // /never-claim-n4 novelty tier (N1/N2/N3). null when Houston hasn't picked yet.
  novelty: "N1" | "N2" | "N3" | null;
  source: "convex" | "static-fallback";
};

const CONVEX_URL =
  process.env.NEXT_PUBLIC_CONVEX_URL || process.env.CONVEX_URL || "";

async function fetchFromConvex(): Promise<LivePaperState[] | null> {
  if (!CONVEX_URL) return null;
  try {
    // Lazy import so the static fallback path doesn't pull in convex/browser
    // when CONVEX_URL is unset.
    const { ConvexHttpClient } = await import("convex/browser");
    // Hand-typed function reference to avoid the Next/Convex build coupling
    // (api.d.ts is regenerated by `npx convex dev`, not us).
    const client = new ConvexHttpClient(CONVEX_URL);
    const result = (await client.query(
      "papers:listAllPaperStates" as unknown as Parameters<
        typeof client.query
      >[0]
    )) as Array<{
      slug: string;
      number: string;
      shortTitle: string;
      status: string;
      currentVersion: string | null;
      lastUpdated: string | null;
      readinessComputed: number;
      openBlockers: number;
      openMajors: number;
      openMinors: number;
      openCaveats: number;
      houstonSignOff: string | null;
      sitePdfPath: string | null;
      focusAreas?: string[];
      novelty?: "N1" | "N2" | "N3" | null;
    }>;
    return result.map((r) => ({
      ...r,
      focusAreas: r.focusAreas ?? [],
      novelty: r.novelty ?? null,
      source: "convex" as const,
    }));
  } catch (err) {
    console.warn("[livePapers] Convex fetch failed, falling back to static:", err);
    return null;
  }
}

function staticFallback(): LivePaperState[] {
  // Merge static papers.ts (richer schema) + live-status.ts (per-paper readiness)
  // into the unified LivePaperState shape.
  const liveByVersion = new Map(liveStatus.papers.map((p) => [p.version, p]));
  return staticPapers.map((p: Paper): LivePaperState => {
    const live = liveByVersion.get(p.version);
    void live;
    return {
      slug: p.slug,
      number: p.number,
      shortTitle: p.title.slice(0, 80),
      status: p.statusVariant === "green" ? "active-drive-to-100" : p.statusVariant,
      currentVersion: p.version,
      lastUpdated: p.lastUpdated,
      readinessComputed: p.readiness,
      openBlockers: 0, // static papers.ts doesn't track these counts
      openMajors: 0,
      openMinors: 0,
      openCaveats: p.path.filter((s) => s.state !== "done").length,
      houstonSignOff: null,
      sitePdfPath: null,
      focusAreas: [],
      novelty: null,
      source: "static-fallback",
    };
  });
}

/**
 * Server-side entry point used by app routes. Tries Convex first,
 * falls back to static if unavailable.
 */
export async function getLivePapers(): Promise<LivePaperState[]> {
  const convex = await fetchFromConvex();
  if (convex && convex.length > 0) return convex;
  return staticFallback();
}

export function isLive(states: LivePaperState[]): boolean {
  return states.length > 0 && states[0].source === "convex";
}

// ──────────────────────────────────────────────────────────────────────
// Gap #1 (closed 2026-06-03) — papers_notables + papers_externalReviews
// fetchers. Both are Convex-only with empty-array fallback; static
// papers.ts does not carry these.
// ──────────────────────────────────────────────────────────────────────

export type Notable = {
  ordinal: number;
  bullet: string;
  citationKey?: string;
};

export type ExternalReview = {
  source:
    | "journal"
    | "arxiv"
    | "houston-paste"
    | "colleague-private"
    | "internal-stage3";
  reviewerLabel: string;
  receivedAt: string;
  blockerCount: number;
  majorCount: number;
  minorCount: number;
  recommendation:
    | "accept"
    | "minor-revisions"
    | "major-revisions"
    | "reject"
    | "pending";
  pdfUrl?: string;
  notes?: string;
};

export async function getNotablesForPaper(
  paperSlug: string
): Promise<Notable[]> {
  if (!CONVEX_URL) return [];
  try {
    const { ConvexHttpClient } = await import("convex/browser");
    const client = new ConvexHttpClient(CONVEX_URL);
    const rows = (await client.query(
      "notables:list" as unknown as Parameters<typeof client.query>[0],
      { paperSlug } as unknown as Parameters<typeof client.query>[1]
    )) as Array<{
      ordinal: number;
      bullet: string;
      citationKey?: string;
    }>;
    return rows.map((r) => ({
      ordinal: r.ordinal,
      bullet: r.bullet,
      citationKey: r.citationKey,
    }));
  } catch (err) {
    console.warn("[livePapers] notables fetch failed:", err);
    return [];
  }
}

// ──────────────────────────────────────────────────────────────────────
// paper_figures fetchers — drive /figures from Convex (seeded by
// tools/seed_paper_figures.mjs from each paper's current .tex). The
// build-time snapshot at site/src/data/figures.ts remains the SSG
// fallback when Convex is unreachable.
// ──────────────────────────────────────────────────────────────────────

export type PaperFigure = {
  paperSlug: string;
  ordinal: number;
  src: string;
  alt: string;
  title: string;
  desc: string;
  paperVersion: string;
  citationLabel?: string;
  status?: "in-paper" | "candidate" | "retracted";
};

export async function getFiguresForPaper(
  paperSlug: string
): Promise<PaperFigure[]> {
  if (!CONVEX_URL) return [];
  try {
    const { ConvexHttpClient } = await import("convex/browser");
    const client = new ConvexHttpClient(CONVEX_URL);
    const rows = (await client.query(
      "figures:list" as unknown as Parameters<typeof client.query>[0],
      { paperSlug } as unknown as Parameters<typeof client.query>[1]
    )) as PaperFigure[];
    return rows;
  } catch (err) {
    console.warn("[livePapers] figures:list fetch failed:", err);
    return [];
  }
}

export async function getAllFiguresGroupedByPaper(): Promise<
  Record<string, PaperFigure[]>
> {
  if (!CONVEX_URL) return {};
  try {
    const { ConvexHttpClient } = await import("convex/browser");
    const client = new ConvexHttpClient(CONVEX_URL);
    const grouped = (await client.query(
      "figures:listAll" as unknown as Parameters<typeof client.query>[0]
    )) as Record<string, PaperFigure[]>;
    return grouped;
  } catch (err) {
    console.warn("[livePapers] figures:listAll fetch failed:", err);
    return {};
  }
}

// ──────────────────────────────────────────────────────────────────────
// Compute pods — drives the /status "Active Compute" panel. Synced from
// RunPod GraphQL via tools/pod_status_sync.mjs.
// ──────────────────────────────────────────────────────────────────────

export type PodJob = {
  name: string;
  paper: string;
  tmuxSession: string;
  status: "queued" | "running" | "done" | "failed";
  etaNote: string;
  outputPath?: string;
};

export type ComputePod = {
  podId: string;
  name: string;
  status: "running" | "exited" | "terminated";
  gpu: string;
  hourlyCostUsd: number;
  startedAt: number;
  totalCostUsd: number;
  purpose: string;
  lastSyncedAt: number;
  jobs?: PodJob[];
};

export async function getRunningPods(): Promise<ComputePod[]> {
  if (!CONVEX_URL) return [];
  try {
    const { ConvexHttpClient } = await import("convex/browser");
    const client = new ConvexHttpClient(CONVEX_URL);
    const rows = (await client.query(
      "pods:listRunning" as unknown as Parameters<typeof client.query>[0]
    )) as ComputePod[];
    return rows;
  } catch (err) {
    console.warn("[livePapers] pods:listRunning fetch failed:", err);
    return [];
  }
}

export async function getExternalReviewsForPaper(
  paperSlug: string
): Promise<ExternalReview[]> {
  if (!CONVEX_URL) return [];
  try {
    const { ConvexHttpClient } = await import("convex/browser");
    const client = new ConvexHttpClient(CONVEX_URL);
    const rows = (await client.query(
      "externalReviews:list" as unknown as Parameters<typeof client.query>[0],
      { paperSlug } as unknown as Parameters<typeof client.query>[1]
    )) as ExternalReview[];
    return rows;
  } catch (err) {
    console.warn("[livePapers] externalReviews fetch failed:", err);
    return [];
  }
}
