#!/usr/bin/env python3
"""
Ledger #7 gate: analytic net-helicity asymmetry Delta_h of the SGWB from the
lab's minimal Einstein-Cartan-Holst (ECH) torsion bounce.

Two independent pieces:

(A) SYMBOLIC (sympy).  Show that in minimal ECH with a Dirac / Weyssenhoff spin
    fluid the parity-odd tensor operator coefficient vanishes identically, and
    that ANY parity-odd quadratic tensor operator on FRW carries exactly one
    explicit power of the comoving momentum k (helicity lambda = +-1 always
    appears as lambda*k through eps^{ijk} k_k).  Hence in the super-Hubble
    regime k*eta_B << 1 the helicity asymmetry is linear in k*eta_B at leading
    order:  Delta_h ~ C * xi_B * (k*eta_B)^n, n >= 1.

(B) NUMERIC (numpy).  Evaluate the best-case bound
        Delta_h(f) = C * xi_B * (f / f_B)
    with xi_B <= 1 (perturbative-unitarity ceiling on the dimensionless
    parity coupling at the bounce) for the PTA / LISA / CMB bands, with the
    bounce scale f_B set by redshifting a horizon-scale mode from the ECH
    bounce temperature.

Conventions that are NOT fixed by the lab's artifacts are flagged in the JSON
under "convention_flags"; no coefficient is invented.
"""
import json, os, sys
import numpy as np
import sympy as sp

OUT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "outputs",
                   "ledger7_chiral_gw_delta_h.json")

res = {"id": "ledger7-chiral-gw-delta-h", "date": "2026-09-03"}

# ----------------------------------------------------------------------
# (A) symbolic
# ----------------------------------------------------------------------
gamma = sp.Symbol('gamma', positive=True)          # Barbero-Immirzi
xi_gamma = gamma**2/(1+gamma**2)                   # ECH note Eq. (4fermi)
s_H = sp.Symbol('s_H')                             # Holst sign convention
kappa, lam = sp.symbols('kappa lambda_src', positive=True)

# on-shell ECH torsion irreps (research/theory_audit/ech_torsion_onshell_2026_08_08)
alpha_ax = -gamma**2*kappa*lam/(2*(gamma**2 + s_H**2))     # axial (4)
beta_tv  = -gamma*kappa*lam*s_H/(4*(gamma**2 + s_H**2))    # trace-vector (4)
ratio    = sp.simplify(beta_tv/alpha_ax)                   # = s_H/(2 gamma)

# Nieh-Yan / parity-odd torsion bilinear, on shell:  O4 = -24 alpha beta (J5.J5)
J5sq = sp.Symbol('J5sq')                                   # (J5 . J5), a TRUE scalar
O4 = sp.simplify(-24*alpha_ax*beta_tv*J5sq)

# The four-fermion contact term generated by eliminating torsion (ECH note):
L4psi = -sp.Rational(3,16)*kappa*xi_gamma*J5sq

# Parity content: J5sq = J5^mu J5_mu is P-even (product of two axial vectors).
# Therefore both O4 and L4psi are P-EVEN functions of the matter fields:
# the Levi-Civita symbol in O4 is fully saturated by the torsion indices.
# The tensor perturbation h_ij couples to these only through the metric,
# i.e. parity-even. => coefficient of the parity-odd tensor operator is 0.
c_parity_odd_minimal_ECH = sp.Integer(0)

# General statement for the quadratic tensor action on FRW.  The unique
# parity-odd scalar density at O(h^2) with two derivatives is the
# gravitational Chern-Simons structure eps^{ijk} h_il d_j h_kl (plus
# derivative descendants).  In helicity basis h_(+-) with eps^{ijk}k_k giving
# lambda*k, every such term carries exactly one explicit power of k relative
# to the parity-even kinetic terms.
k, etaB, xiB, aB = sp.symbols('k eta_B xi_B a_B', positive=True)
lam_hel = sp.Symbol('lambda_hel')          # +-1
# mode equation:  u'' + (k^2 - lambda_hel * k * Lam(eta)/a - a''/a) u = 0
# with Lam(eta)/a = xi_B / (a_B eta_B^2) * shape(eta) [dimension 1/length^2 * length]
# ratio of the parity-odd term to the dominant super-Hubble term a''/a ~ 1/eta_B^2:
suppression = sp.simplify((lam_hel*k*xiB/etaB)/(1/etaB**2))   # = lambda k xi_B eta_B
res["symbolic"] = {
    "xi_gamma_gamma2_over_1plusgamma2": sp.srepr(xi_gamma),
    "beta_over_alpha_onshell": str(ratio),
    "O4_onshell": str(sp.simplify(O4)),
    "L4psi": str(L4psi),
    "parity_of_J5sq": "even (axial x axial = true scalar)",
    "parity_odd_tensor_coefficient_minimal_ECH": str(c_parity_odd_minimal_ECH),
    "superhubble_suppression_factor": str(suppression),
    "conclusion": ("minimal ECH + Dirac/Weyssenhoff spin fluid has NO parity-odd "
                   "operator at O(h^2); and ANY parity-odd tensor operator is "
                   "linear in lambda*k, hence O(k*eta_B) suppressed super-Hubble"),
}
# numeric checks of gamma-dependent factors at the lab's values
res["symbolic"]["xi_gamma_numeric"] = {
    "gamma=0.2375": float(xi_gamma.subs(gamma, sp.Rational(19, 80))),
    "gamma=0.274":  float(xi_gamma.subs(gamma, sp.Rational(137, 500))),
}
res["symbolic"]["beta_over_alpha_numeric_sH_plus1"] = {
    "gamma=0.2375": float((ratio).subs({s_H: 1, gamma: sp.Rational(19, 80)})),
    "gamma=0.274":  float((ratio).subs({s_H: 1, gamma: sp.Rational(137, 500)})),
}

# ----------------------------------------------------------------------
# (B) numeric: best-case Delta_h in each band
# ----------------------------------------------------------------------
# Horizon-scale mode produced at temperature T_* redshifts to (standard result,
# e.g. Maggiore, "Gravitational Waves" Vol.2 Eq. (22.30); g_* = 106.75):
#   f_0 ~ 1.65e-7 Hz * (T_*/GeV) * (g_*/100)^{1/6}
def f0_of_T(T_GeV, gstar=106.75):
    return 1.65e-7 * T_GeV * (gstar/100.0)**(1.0/6.0)

bounce_scales = {
    # label: bounce temperature T_B in GeV (the ECH bounce density is set by
    # kappa^2 s^2 ~ rho; the lab has no committed rho_c number, so a range is
    # scanned between the GUT boundary used in the ECH note and M_Pl)
    "T_B = 1e16 GeV (GUT boundary, ECH note mu_UV)": 1.0e16,
    "T_B = 1.22e19 GeV (M_Pl, ECH note)":            1.22e19,
}
bands = {
    "PTA (nHz)":            1.0e-8,
    "LISA (mHz)":           1.0e-3,
    "LIGO/ET (100 Hz)":     1.0e2,
    "CMB B-mode (k ~ 0.005 Mpc^-1)": 3.0e-17,
}
# detectability thresholds on Delta_h from the literature (order of magnitude,
# assuming an SGWB is detected at all in that band):
det = {
    "PTA (nHz)": ("O(1); circular polarisation only accessible through the "
                  "anisotropic/dipole component (Kato & Soda 2016; "
                  "Belgacem & Kamionkowski 2020)"),
    "LISA (mHz)": ("O(1); an isotropic V-mode is BLIND to a single planar "
                   "constellation (Seto & Taruya 2007, 2008) - needs the "
                   "kinematic dipole (Domcke et al. 2020) or a second detector"),
    "LIGO/ET (100 Hz)": "O(1) with a network of >=2 detectors (Seto 2008)",
    "CMB B-mode (k ~ 0.005 Mpc^-1)": ("O(1) chirality AND r >~ 1e-2 for a TB/EB "
                                      "detection (Gluscevic & Kamionkowski 2010; "
                                      "Gerbino et al. 2016; LiteBIRD forecast)"),
}
XI_B_CEILING = 1.0   # dimensionless parity coupling at the bounce, <= 1 by
                     # perturbative unitarity (|delta omega^2| < omega^2)
C_ORDER1 = 1.0       # O(1) matching constant, set to its maximum

rows = []
for blab, T in bounce_scales.items():
    fB = f0_of_T(T)
    for band, f in bands.items():
        d = C_ORDER1 * XI_B_CEILING * (f / fB)
        rows.append({"bounce_scale": blab, "f_B_today_Hz": fB, "band": band,
                     "f_Hz": f, "k_eta_B": f / fB, "Delta_h_max": d,
                     "detectable_threshold": det[band],
                     "orders_of_magnitude_short": float(-np.log10(d))})
res["numeric"] = {
    "formula": "Delta_h(f) = C * xi_B * (f/f_B),  C = O(1), xi_B <= 1",
    "f_B_definition": "horizon-scale mode at the bounce redshifted to today, f_0 = 1.65e-7 Hz (T_*/GeV)(g_*/100)^(1/6)",
    "rows": rows,
}
res["verdict"] = {
    "Q1": "NO parity-odd O(h^2) operator in minimal ECH + Dirac/Weyssenhoff spin fluid",
    "Q2": "coefficient identically zero; a nonzero one needs a dynamical Immirzi/Nieh-Yan pseudoscalar (ad-hoc w.r.t. the minimal model)",
    "Q3": "Delta_h = O(k eta_B) -> <= 1e-12 (LISA), 1e-17 (PTA), 1e-27 (CMB) even at the unitarity ceiling",
    "Q4": "every band needs Delta_h = O(1); short by >=12 orders of magnitude",
    "gate": "CLOSE WITH REASON (O(epsilon), and requires an ad-hoc ingredient)",
}
res["convention_flags"] = [
    "Holst sign s_H is not fixed by the lab's artifacts; both signs flip O4's sign only.",
    "The ECH note fixes gamma^2/(1+gamma^2) but no committed numerical rho_c / T_B: a two-point range (1e16 GeV, M_Pl) is scanned instead of inventing one.",
    "C = O(1) matching constant is set to its maximum (1.0); it is model-dependent and is NOT computed here.",
    "xi_B is bounded above by perturbative unitarity, not derived from ECH (in minimal ECH it is exactly 0).",
]
os.makedirs(os.path.dirname(OUT), exist_ok=True)
with open(OUT, "w") as fh:
    json.dump(res, fh, indent=2)
print(json.dumps(res["symbolic"], indent=2))
for r in rows:
    print(f'{r["bounce_scale"][:22]:24s} {r["band"]:32s} f_B={r["f_B_today_Hz"]:.3e} Hz  '
          f'k eta_B={r["k_eta_B"]:.3e}  Delta_h<={r["Delta_h_max"]:.3e}')
print("\nGATE:", res["verdict"]["gate"])
print("written:", OUT)
