"""
ttt_baseline.py — Standard Tidal Torque Theory (TTT) baseline
=============================================================

Implements the standard TTT predictions for halo angular momentum,
spin parameter distribution, and handedness probability.

Key references:
  - White, S. D. M. (1984). Angular momentum growth in protogalaxies.
    ApJ, 286, 38.  [Eq. 1: TTT angular momentum integral]
  - Porciani, C., Dekel, A., & Hoffman, Y. (2002). Testing tidal-torque
    theory. I. Spin amplitude and direction. MNRAS, 332, 325.
    [Eq. 5: spin parameter distribution; Eq. 12: alignment correlation]

Physics summary:
  The angular momentum of a protogalactic region is generated by the
  misalignment between the inertia tensor I_{ij} and the tidal tensor
  T_{ij} of the gravitational potential:

    L_i = epsilon_{ijk} * integral[ rho(x) * x_j * (dPhi/dx_k) ] d^3x
                                                                   [Eq. 1]

  In the TTT approximation (linear theory):

    L_i ~ epsilon_{ijk} * T_{jl} * I_{lk}                          [Eq. 2]

  The dimensionless spin parameter (Peebles 1969):

    lambda = J * |E|^{1/2} / (G * M^{5/2})                         [Eq. 3]

  Standard TTT predicts:
    - log-normal distribution of lambda with <lambda> ~ 0.035,
      sigma_{ln lambda} ~ 0.5                                      [Eq. 4]
    - NO preferred handedness: P(CW) = P(CCW) = 0.5 (by parity)   [Eq. 5]
"""

import numpy as np
from scipy import stats


class TidalTorqueBaseline(object):
    """
    Standard Tidal Torque Theory (TTT) baseline predictions.

    The TTT generates angular momentum from the misalignment of the
    inertia and tidal tensors (White 1984, Eq. 2). Under parity
    symmetry, there is no preferred handedness.

    Parameters
    ----------
    lambda_mean : float
        Mean spin parameter <lambda>. Standard value: 0.035
        (Porciani et al. 2002, Table 1).
    sigma_lnlambda : float
        Width of the log-normal spin distribution.
        Standard value: 0.5 (Porciani et al. 2002, Eq. 5).
    """

    def __init__(self, lambda_mean=0.035, sigma_lnlambda=0.5):
        self.lambda_mean = lambda_mean
        self.sigma_lnlambda = sigma_lnlambda

        # Log-normal parameters: if X ~ LogNormal(mu, sigma),
        # then <X> = exp(mu + sigma^2/2)
        # => mu = ln(<X>) - sigma^2/2
        self.mu_ln = np.log(lambda_mean) - 0.5 * sigma_lnlambda**2
        self.sigma_ln = sigma_lnlambda

    def spin_parameter_distribution(self, M_halo=1e12, z=0.0, n_points=500):
        """
        Returns the log-normal distribution of the spin parameter lambda.

        Standard TTT prediction: P(lambda) is log-normal with
        <lambda> ~ 0.035 and sigma_{ln lambda} ~ 0.5 (Porciani+2002, Eq. 5).

        The distribution is approximately independent of halo mass and
        redshift in the standard picture, though there is mild mass
        dependence in simulations. Here we apply a small empirical
        correction factor.

        Parameters
        ----------
        M_halo : float
            Halo mass in solar masses (for mild mass correction).
        z : float
            Redshift (for mild redshift correction).
        n_points : int
            Number of points in the returned distribution.

        Returns
        -------
        lambda_arr : ndarray
            Array of spin parameter values.
        pdf_arr : ndarray
            Probability density at each lambda value.
        """
        # Mild mass correction: lambda scales weakly with M
        # (Hetznecker & Burkert 2006: delta_mu ~ 0.05 * log10(M/1e12))
        mass_correction = 0.05 * np.log10(max(M_halo, 1e8) / 1e12)

        # Mild redshift correction: lambda grows slightly with z
        # (empirical from Bett+2007: delta_mu ~ 0.02 * z)
        z_correction = 0.02 * z

        mu_corrected = self.mu_ln + mass_correction + z_correction

        # Log-normal distribution
        lambda_arr = np.linspace(1e-4, 0.25, n_points)
        pdf_arr = stats.lognorm.pdf(
            lambda_arr,
            s=self.sigma_ln,
            scale=np.exp(mu_corrected)
        )

        return lambda_arr, pdf_arr

    def handedness_probability(self):
        """
        Returns the probability of CW rotation under standard TTT.

        By parity symmetry, TTT predicts exactly P(CW) = 0.5 [Eq. 5].
        The tidal torque mechanism has no preferred handedness because
        the cross product L_i = epsilon_{ijk} T_{jl} I_{lk} is
        equivariant under parity: P -> -P implies L -> -L, so the
        projection along any fixed axis is equally likely to be
        positive or negative.

        Returns
        -------
        p_cw : float
            Probability of clockwise rotation. Always 0.5.
        """
        return 0.5

    def alignment_correlation(self, r_sep, r0=5.0, gamma=1.5):
        """
        Standard spin-LSS alignment correlation function.

        Measures the tendency of halo spins to align with nearby
        large-scale structure filaments (Porciani+2002, Eq. 12).
        This is NOT a handedness effect — it describes the alignment
        of the spin AXIS, not its direction.

        We use a simple power-law model:
            xi_align(r) = (r0 / r)^gamma                           [Eq. 6]

        Parameters
        ----------
        r_sep : float or ndarray
            Separation in Mpc/h.
        r0 : float
            Correlation length in Mpc/h. Default: 5.0.
        gamma : float
            Power-law index. Default: 1.5.

        Returns
        -------
        xi : float or ndarray
            Alignment correlation at the given separation(s).
        """
        r_sep = np.atleast_1d(np.array(r_sep, dtype=float))
        xi = np.where(r_sep > 0, (r0 / r_sep) ** gamma, np.inf)
        return xi

    def expected_dipole_amplitude(self):
        """
        Expected galaxy spin dipole amplitude under standard TTT.

        Returns exactly 0.0 — TTT is parity symmetric, so there is
        no dipole in the CW/CCW distribution.

        Returns
        -------
        A0 : float
            Dipole amplitude. Always 0.0.
        """
        return 0.0

    def summary(self):
        """Print a summary of the TTT baseline predictions."""
        lines = [
            "=" * 60,
            "Tidal Torque Theory — Baseline Predictions",
            "=" * 60,
            "Spin parameter:",
            "  <lambda> = %.4f" % self.lambda_mean,
            "  sigma_ln(lambda) = %.2f" % self.sigma_lnlambda,
            "  mu_ln = %.4f" % self.mu_ln,
            "",
            "Handedness:",
            "  P(CW) = %.1f  (parity symmetric)" % self.handedness_probability(),
            "",
            "Dipole amplitude:",
            "  A_0 = %.1f  (null prediction)" % self.expected_dipole_amplitude(),
            "",
            "References:",
            "  White (1984), ApJ 286, 38",
            "  Porciani, Dekel & Hoffman (2002), MNRAS 332, 325",
            "=" * 60,
        ]
        return "\n".join(lines)


if __name__ == "__main__":
    # ---- Self-test and demonstration ----
    print("Running TTT baseline self-test...\n")

    ttt = TidalTorqueBaseline()
    print(ttt.summary())

    # Test spin parameter distribution
    lam, pdf = ttt.spin_parameter_distribution(M_halo=1e12, z=0.0)
    peak_idx = np.argmax(pdf)
    print("\nSpin distribution peak at lambda = %.4f" % lam[peak_idx])
    # np.trapezoid replaces np.trapz in NumPy 2.x
    _trapz = getattr(np, "trapezoid", getattr(np, "trapz", None))
    print("Mean lambda (numerical) = %.4f" % _trapz(lam * pdf, lam))

    # Test handedness
    assert ttt.handedness_probability() == 0.5, "Handedness must be 0.5"
    print("Handedness test: PASSED (P(CW) = 0.5)")

    # Test dipole
    assert ttt.expected_dipole_amplitude() == 0.0, "Dipole must be 0.0"
    print("Dipole test: PASSED (A_0 = 0.0)")

    # Test alignment correlation
    r = np.array([1.0, 5.0, 10.0, 50.0])
    xi = ttt.alignment_correlation(r)
    print("\nAlignment correlation xi(r):")
    for ri, xi_i in zip(r, xi):
        print("  r = %.1f Mpc/h  ->  xi = %.4f" % (ri, xi_i))

    print("\nAll tests passed.")
