#!/usr/bin/env python3
"""PSU gates S1/S2 (+S3 math): label-resolved composition and a well-defined criterion.
Exact sympy. Inputs are the frozen closed forms of threading_map_second_order_2026_09_04.json
(map pieces) and fnl_monopole_adjudication_2026_09_03 (in-in kernel). No new constraint solve.
Output: psu_gates_S1_S2_2026_09_04.json."""
import json, hashlib, sympy as sp
eps, mu, w = sp.symbols('epsilon mu w', real=True)
kL, eta, etaf, etai, m, p = sp.symbols('k_L eta eta_f eta_i m p', positive=True)
R = sp.Rational
OUT = {}
def poly_mu(f):
    f = sp.expand(sp.simplify(f)); return {'const': sp.simplify(f.coeff(mu, 0)), 'mu2': sp.simplify(f.coeff(mu, 2))}
def mono(f): return sp.simplify(poly_mu(f)['const'] + poly_mu(f)['mu2'] / 3)
def S(d): return {k: str(v) for k, v in d.items()}

# ---------------- S1: label-resolved composition ----------------
lam = 1 - eps / 3
f_inin = R(5, 12) * (eps**2 * mu**2 - eps**2 + 6 * eps - 12)          # adjudication, general constant eps
# frozen map pieces (threading_map_second_order json, f_NL normalisation of delta N_c)
zlap = 5 * eps / (3 - eps)**2
psi2 = 5 * eps * (-2 * eps**2 + 11 * eps - 24) / (8 * (3 - eps)**2) + 5 * eps * (2 * eps**2 - 9 * eps + 12) / (8 * (3 - eps)**2) * mu**2
grad = -5 * eps / (4 * (3 - eps)**2) + 15 * eps / (4 * (3 - eps)**2) * mu**2
wl_fin = 5 * eps**2 / (8 * (3 - eps)**2) - 15 * eps**2 / (8 * (3 - eps)**2) * mu**2
lab_init = 15 * eps / (4 * (3 - eps)**2) - 45 * eps / (4 * (3 - eps)**2) * mu**2     # rigid translation x_f -> x_i
wl_initextra = -5 * eps**2 / (4 * (3 - eps)**2) + 15 * eps**2 / (4 * (3 - eps)**2) * mu**2
f_map_fin = sp.simplify(zlap + psi2 + grad + wl_fin)
f_map_init = sp.simplify(f_map_fin + lab_init + wl_initextra)
T_label = sp.simplify(lab_init + wl_initextra)                       # the label-translation term
assert sp.simplify(f_map_fin + R(5, 4) * eps * (1 - mu**2)) == 0
assert sp.simplify(f_map_init - 5 * eps / (4 * (3 - eps)) * ((eps - 2) - eps * mu**2)) == 0
assert sp.simplify(T_label - 5 * eps / (4 * (3 - eps)) * (1 - 3 * mu**2)) == 0
assert mono(T_label) == 0 and mono(lab_init) == 0 and mono(wl_initextra) == 0
f_dN_init = sp.simplify(f_inin / lam + f_map_init)
f_dN_fin = sp.simplify(f_inin / lam + f_map_fin)
assert f_dN_init == -5
assert sp.simplify(f_dN_fin - (-R(15, 4) * (eps - 4) / (eps - 3) + R(15, 4) * eps / (3 - eps) * mu**2)) == 0
assert mono(f_dN_fin) == -5 and mono(f_map_fin) == mono(f_map_init) == -5 * eps / 6
# the wrong composition (paper Eq. 3 as printed: final-label map + initial-label total -5)
wrong = sp.simplify(f_inin / lam + f_map_fin)
assert wrong.subs(eps, R(3, 2)) != -5
cases = {'dust_eps_3_2': R(3, 2), 'radiation_like_eps_2': 2, 'eps_1': 1}
OUT['S1'] = {
    'f_map_final_label': S(poly_mu(f_map_fin)), 'f_map_initial_label': S(poly_mu(f_map_init)),
    'label_translation_term_T': S(poly_mu(T_label)), 'T_monopole': str(mono(T_label)),
    'f_dN_initial_label': S(poly_mu(f_dN_init)), 'f_dN_final_label': S(poly_mu(f_dN_fin)),
    'general_w': {'f_map_init': str(sp.simplify(f_map_init.subs(eps, R(3, 2) * (1 + w)))),
                  'f_dN_final': str(sp.simplify(f_dN_fin.subs(eps, R(3, 2) * (1 + w))))},
    'at_eps': {k: {'f_map_fin': S(poly_mu(f_map_fin.subs(eps, v))), 'f_map_init': S(poly_mu(f_map_init.subs(eps, v))),
                   'f_dN_init': S(poly_mu(f_dN_init.subs(eps, v))), 'f_dN_fin': S(poly_mu(f_dN_fin.subs(eps, v))),
                   'printed_Eq3_composition': S(poly_mu(wrong.subs(eps, v)))} for k, v in cases.items()},
    'usr_limit_eps_to_0': {'f_map_init': str(sp.limit(f_map_init, eps, 0)), 'f_map_fin': str(sp.limit(f_map_fin, eps, 0)),
                           'T': str(sp.limit(T_label, eps, 0))},
    'attractor': 'zeta_L constant => chi=0, div N^i = O(k^2): every map piece is generated by eps*zeta_dot_L and vanishes; map = identity'}
print('S1 OK: init', f_dN_init, '| fin', poly_mu(f_dN_fin), '| T', poly_mu(T_label))

# ---------------- S2: well-defined criterion + the gradient term ----------------
# Super-Hubble comoving-gauge divergence, exact in k:  div N^i = (eps/c_s^2) zeta_dot - lap(zeta)/(a^2 H).
# From a FLAT initial slice t_i (super-Hubble) to the comoving final slice t_f, along the fluid worldline:
#   delta N_c = zeta_f - (1/3) int_{t_i}^{t_f} div N^i dt   =>   lambda = delta N_c/zeta_f = 1 - I/3 + G
#   I = (1/zeta_f) int (eps/c_s^2) zeta_dot dt   (growth-weighted INTEGRAL; well defined for every history)
#   G = (1/(3 zeta_f)) int lap(zeta)/(a^2 H) dt = -(k^2/(3 zeta_f)) int zeta/(aH) d eta   (the dropped gradient term)
# Power-law background: x = -eta > 0, a = x^p (p = 1/(eps-1)), calH = a'/a = -p/x, k/(aH) = k x/p; growing mode zeta = C x^{-m}.
x, xf, xi_, C = sp.symbols('x x_f x_i C', positive=True)
def G_of(zeta_x, pp):           # -(k^2/(3 zeta_f)) * int_{eta_i}^{eta_f} zeta/calH d eta,  d eta = -dx
    calH = -pp / x
    integ = sp.integrate(zeta_x / calH, (x, xi_, xf))          # d eta = -dx  ->  int_{eta_i}^{eta_f} = -int_{x_i}^{x_f}
    return sp.simplify(-(kL**2 / (3 * zeta_x.subs(x, xf))) * (-integ))
def I_of(zeta_x, eps_x):        # (1/zeta_f) int eps dzeta over the interval (constant eps pulls out)
    return sp.simplify(sp.integrate(eps_x * sp.diff(zeta_x, x), (x, xi_, xf)) / zeta_x.subs(x, xf))
S2 = {}
# (a) general constant-eps growing mode, m = (3-eps)/(eps-1), p = 1/(eps-1)
zg = C * x**(-m)
I_g = I_of(zg, eps); G_g = G_of(zg, p)
S2['general_growing'] = {'I': str(I_g), 'lambda': str(sp.simplify(1 - I_g / 3)), 'G_dropped_term': str(G_g)}
assert sp.simplify(I_g - eps * (1 - (xf / xi_)**m)) == 0
# dust: eps=3/2 -> p=2, m=3
zd = C * x**(-3); I_d = I_of(zd, R(3, 2)); G_d = G_of(zd, 2)
G_d_lead = sp.simplify(sp.limit(G_d / (kL * xf)**2, xi_, sp.oo))   # leading term in units of (k eta_f)^2
S2['dust'] = {'I': str(I_d), 'I_limit_xi_to_inf': str(sp.limit(I_d, xi_, sp.oo)), 'G': str(G_d),
              'G_leading_over_(k_eta_f)^2': str(G_d_lead), 'k_over_aH_f': 'k x_f / p = k eta_f / 2'}
assert sp.limit(I_d, xi_, sp.oo) == R(3, 2) and G_d_lead == R(1, 6)
# (b) attractor: constant zeta (m=0); shown for de Sitter p=-1 and a generic p
za = C + 0 * x
I_a = I_of(za, eps); G_a_dS = G_of(za, -1); G_a_p = G_of(za, p)
S2['attractor'] = {'I': str(I_a), 'lambda': str(1 - I_a / 3), 'G_deSitter': str(G_a_dS), 'G_general_p': str(G_a_p),
                   'mean_normalisation_int_dzeta_over_(zeta_f-zeta_i)': '0/0 (undefined)  <- the audit finding; I is 0, well defined'}
assert I_a == 0
# (c) ekpyrosis dominant (constant) mode: identical to (b) with p = 1/(eps-1) small; the decaying mode never sets zeta_f
S2['ekpyrosis_dominant_mode'] = {'I': '0', 'lambda': '1', 'G': str(sp.simplify(G_a_p.subs(p, 1 / (eps - 1)))), 'note': 'constant mode; same as attractor'}
# (d) USR: eps = eps_s (a/a_s)^-6, zeta ~ a^3 (de Sitter a = 1/x), start at x_s with zeta_s frozen from slow roll
es, ef = sp.symbols('epsilon_s epsilon_f', positive=True)
zu = C * x**(-3); eu = es * (x / xi_)**6            # a/a_s = x_s/x with x_s = x_i
I_u = I_of(zu, eu)
I_u = sp.simplify(I_u.subs(xi_, xf * (es / ef)**R(1, 6)))       # eps_f = eps_s (x_f/x_s)^6
S2['USR'] = {'I': str(I_u), 'lambda': str(sp.simplify(1 - I_u / 3)), 'G_leading_over_(k_eta_f)^2': str(sp.simplify(sp.limit(G_of(zu, -1) / (kL * xf)**2, xi_, sp.oo)))}
assert sp.simplify(I_u - (sp.sqrt(es * ef) - ef)) == 0
# (e) kination eps=3: zeta = A + B ln x (log growth) -> I = 3 (1 - zeta_i/zeta_f); integrated form only
A, B = sp.symbols('A B', real=True); zk = A + B * sp.log(x)
I_k = I_of(zk, 3); S2['kination'] = {'I': str(sp.simplify(I_k)), 'lambda': str(sp.simplify(1 - I_k / 3)), 'note': 'lambda = zeta_i/zeta_f; ->0 only as x_i->oo'}
S2['criterion'] = ('delta N_c = zeta_f [1 - I/3 + O(k_L^2/a^2H^2)],  I = (1/zeta_L,f) int_{t_i}^{t_f} (eps/c_s^2) zeta_dot_L dt, '
                   'flat super-Hubble initial slice t_i; SU = in-in at linear order iff I -> 0; the "mean" <X>_zeta = I zeta_f/(zeta_f - zeta_i) exists only when zeta_i != zeta_f')
OUT['S2'] = S2
print('S2 OK: I_general', I_g, '| G_dust lead', G_d_lead, '| I_USR', I_u, '| I_attractor', I_a)

# ---------------- S3 (math level): change of variable, not a discrepancy ----------------
# B_{dN_c} = lam^3 B_zeta + lam^2 P_L [M(k_L,q)P(q) + M(k_L,p)P(p)]  is linear and invertible for lam != 0:
# B_zeta = lam^-3 (B_{dN_c} - lam^2 P_L[...]).  Both directions exact at second order; nothing physical is lost.
inv_check = sp.simplify(lam * (f_dN_init - f_map_init) - f_inin)        # invert the initial-label composition
assert inv_check == 0
inin_mono_from_dN = sp.simplify(lam * (-5 - mono(f_map_init)))
assert sp.simplify(inin_mono_from_dN + 5 * (eps - 3) * (eps - 6) / 18) == 0
OUT['S3_math'] = {
    'statement': ('f_dN = f_inin/lam + f_map(label) is an exact invertible change of variable at second order (lam != 0). '
                  'Variable-dependent: the numbers f_NL(zeta) = -35/16+15/16 mu^2, f_NL(dN_c, initial label) = -5, '
                  'f_NL(dN_c, final label) = -25/4+15/4 mu^2 at eps=3/2. Variable-independent: the map (lam, M) and any '
                  'observable defined through a stated variable. The isotropic SU computes dN_c(initial label) and the '
                  'standard delta-N formula IDENTIFIES it with zeta; that identification is what fails, by 1-lam = I/3 '
                  'and f_map, iff I = O(1). The criterion is the condition for dN_c = zeta_Mald.'),
    'inversion_recovers_inin_monopole': str(inin_mono_from_dN), 'lam_zero_at': 'eps=3 (kination): dN_c has no linear response, map not invertible there'}
OUT['verdicts'] = {'S1': 'RESOLVED (equations): both labels derived, composition validated all constant eps',
                   'S2': 'RESOLVED (equations): criterion restated as I with flat super-Hubble initial slice; gradient term O(k_L^2/a^2H^2) restored and bounded; 0/0 rows now I=0',
                   'S3': 'RESOLVED at the math level (exact invertible change of variable; failure = identification dN_c=zeta); framing/title is a Houston R3/R6 decision'}
json.dump(OUT, open('psu_gates_S1_S2_2026_09_04.json', 'w'), indent=1, default=str)
print('json written; sha256', hashlib.sha256(open('psu_gates_S1_S2_2026_09_04.json', 'rb').read()).hexdigest()[:16])
