#!/usr/bin/env python3
"""PSU gates S1/S2 (+S3 math): label-resolved composition and a well-defined criterion.
Exact sympy. Inputs are the frozen closed forms of threading_map_second_order_2026_09_04.json
(map pieces) and fnl_monopole_adjudication_2026_09_03 (in-in kernel). No new constraint solve.
Output: psu_gates_S1_S2_2026_09_04.json."""
import json, hashlib, sympy as sp
eps, mu, w = sp.symbols('epsilon mu w', real=True)
kL, eta, etaf, etai, m, p = sp.symbols('k_L eta eta_f eta_i m p', positive=True)
R = sp.Rational
OUT = {}
def poly_mu(f):
    f = sp.expand(sp.simplify(f)); return {'const': sp.simplify(f.coeff(mu, 0)), 'mu2': sp.simplify(f.coeff(mu, 2))}
def mono(f): return sp.simplify(poly_mu(f)['const'] + poly_mu(f)['mu2'] / 3)
def S(d): return {k: str(v) for k, v in d.items()}

# ---------------- S1: label-resolved composition ----------------
lam = 1 - eps / 3
f_inin = R(5, 12) * (eps**2 * mu**2 - eps**2 + 6 * eps - 12)          # adjudication, general constant eps
# frozen map pieces (threading_map_second_order json, f_NL normalisation of delta N_c)
zlap = 5 * eps / (3 - eps)**2
psi2 = 5 * eps * (-2 * eps**2 + 11 * eps - 24) / (8 * (3 - eps)**2) + 5 * eps * (2 * eps**2 - 9 * eps + 12) / (8 * (3 - eps)**2) * mu**2
grad = -5 * eps / (4 * (3 - eps)**2) + 15 * eps / (4 * (3 - eps)**2) * mu**2
wl_fin = 5 * eps**2 / (8 * (3 - eps)**2) - 15 * eps**2 / (8 * (3 - eps)**2) * mu**2
lab_init = 15 * eps / (4 * (3 - eps)**2) - 45 * eps / (4 * (3 - eps)**2) * mu**2     # rigid translation x_f -> x_i
wl_initextra = -5 * eps**2 / (4 * (3 - eps)**2) + 15 * eps**2 / (4 * (3 - eps)**2) * mu**2
f_map_fin = sp.simplify(zlap + psi2 + grad + wl_fin)
f_map_init = sp.simplify(f_map_fin + lab_init + wl_initextra)
T_label = sp.simplify(lab_init + wl_initextra)                       # the label-translation term
assert sp.simplify(f_map_fin + R(5, 4) * eps * (1 - mu**2)) == 0
assert sp.simplify(f_map_init - 5 * eps / (4 * (3 - eps)) * ((eps - 2) - eps * mu**2)) == 0
assert sp.simplify(T_label - 5 * eps / (4 * (3 - eps)) * (1 - 3 * mu**2)) == 0
assert mono(T_label) == 0 and mono(lab_init) == 0 and mono(wl_initextra) == 0
f_dN_init = sp.simplify(f_inin / lam + f_map_init)
f_dN_fin = sp.simplify(f_inin / lam + f_map_fin)
assert f_dN_init == -5
assert sp.simplify(f_dN_fin - (-R(15, 4) * (eps - 4) / (eps - 3) + R(15, 4) * eps / (3 - eps) * mu**2)) == 0
assert mono(f_dN_fin) == -5 and mono(f_map_fin) == mono(f_map_init) == -5 * eps / 6
# the wrong composition (paper Eq. 3 as printed: final-label map + initial-label total -5)
wrong = sp.simplify(f_inin / lam + f_map_fin)
assert wrong.subs(eps, R(3, 2)) != -5
cases = {'dust_eps_3_2': R(3, 2), 'radiation_like_eps_2': 2, 'eps_1': 1}
OUT['S1'] = {
    'f_map_final_label': S(poly_mu(f_map_fin)), 'f_map_initial_label': S(poly_mu(f_map_init)),
    'label_translation_term_T': S(poly_mu(T_label)), 'T_monopole': str(mono(T_label)),
    'f_dN_initial_label': S(poly_mu(f_dN_init)), 'f_dN_final_label': S(poly_mu(f_dN_fin)),
    'general_w': {'f_map_init': str(sp.simplify(f_map_init.subs(eps, R(3, 2) * (1 + w)))),
                  'f_dN_final': str(sp.simplify(f_dN_fin.subs(eps, R(3, 2) * (1 + w))))},
    'at_eps': {k: {'f_map_fin': S(poly_mu(f_map_fin.subs(eps, v))), 'f_map_init': S(poly_mu(f_map_init.subs(eps, v))),
                   'f_dN_init': S(poly_mu(f_dN_init.subs(eps, v))), 'f_dN_fin': S(poly_mu(f_dN_fin.subs(eps, v))),
                   'printed_Eq3_composition': S(poly_mu(wrong.subs(eps, v)))} for k, v in cases.items()},
    'usr_limit_eps_to_0': {'f_map_init': str(sp.limit(f_map_init, eps, 0)), 'f_map_fin': str(sp.limit(f_map_fin, eps, 0)),
                           'T': str(sp.limit(T_label, eps, 0))},
    'attractor': 'zeta_L constant => chi=0, div N^i = O(k^2): every map piece is generated by eps*zeta_dot_L and vanishes; map = identity'}
print('S1 OK: init', f_dN_init, '| fin', poly_mu(f_dN_fin), '| T', poly_mu(T_label))
