#!/usr/bin/env python3
r"""
TRACK A2 / NEXT_SCIENCE_LEDGER item #2 -- transmission of the matter-contraction
f_NL through an explicit nonsingular bounce.

WHAT THIS ADDS OVER THE COMMITTED PRIOR WORK IN THIS DIRECTORY
--------------------------------------------------------------
  g1_gradient_transmission_scheme.py  (phase 1): effective-FLUID Mukhanov-Sasaki
      variable -> the gradient-transmission coefficient has no scheme-independent
      limit (c ~ dcut^{-1}); mechanism = the H = 0 pole in z^2 = a^2(rho+p)/(c_s^2 H^2).
  g1_dressedmetric_transmission.py    (phase 2): the bounded dressed geometric
      potential a''/a cures that regulator pathology; absolute coefficient still
      IC-epoch sensitive.
  g1_dressedmetric_ic_close.py        (phase 3): with mode-by-mode adiabatic-vacuum
      ICs the CONSTANT (Weinberg) branch transmits with T_c(k) = 1 identically,
      hence "|delta f_NL| <= 6.8e-8".

Phase 3's T_c = 1 is a statement about the CONSTANT branch alone.  The physical
adiabatic-vacuum mode in a matter contraction is NOT constant-branch dominated:
this script shows it is dominated by the branch that grows in contraction, by the
factor |r| = 9 A^2 I_inf / k^3 >> 1, and it is that branch which carries the
matter-contraction f_NL.  Transmission of the PHYSICAL super-Hubble curvature
perturbation is therefore NOT unity, and the corresponding f_NL transmission
coefficient is computed here in THREE explicit nonsingular bounces and TWO
Mukhanov-Sasaki variable schemes.

SET-UP (units 8 pi G = 1, a_bounce = 1, c_s = 1)
------------------------------------------------
  mu'' + (k^2 - W) mu = 0,  zeta = mu/z, with the geometric / dressed-metric
  prescription  z = a,  W = a''/a  (the SCHEME LABEL on every number below);
  the effective-fluid variable z^2 = a^2(rho+p)/(c_s^2 H^2) appears as a contrast.

  Exact k = 0 branch basis, valid in ANY FRW background:
      zeta_C = 1                              (constant / Weinberg branch)
      zeta_G = J(eta) = int_0^eta deta'/a'^2   (grows in contraction)
  so the general super-Hubble solution is  zeta(eta) = C1 + C2 J(eta),  and the
  transfer from any epoch to any other is the K-INDEPENDENT linear map
      (C1, C2) -> (C1, C2),   zeta(eta_2)/zeta(eta_1) = (C1 + C2 J_2)/(C1 + C2 J_1).
  In matter asymptotics a -> A tau^2 (tau = eta - eta_off) the exact finite-k
  basis is the nu = 3/2 pair S(u) = sin u/u - cos u  (-> constant branch) and
  C(u) = cos u/u + sin u  (-> growing branch), u = k tau, and the adiabatic
  (Bunch-Davies) vacuum is the exact matter solution
      mu_vac = e^{-iu}(1 - i/u)/sqrt(2k) = (-S(u) - i C(u))/sqrt(2k).          [S1]
  Projecting [S1] gives, in closed form,
      C1 = alpha_- (1 + r),   C2 = beta_-,   r = beta_- I_inf/alpha_- = -9 i A^2 I_inf/k^3.

  TRANSMISSION OF f_NL.  Because the super-Hubble transfer is a k-independent
  LINEAR rescaling of the whole zeta field between a handoff epoch -eta_h and
  late times,
      lambda(eta_h) = zeta(+inf)/zeta(-eta_h) = (C1 + C2 I_inf)/(C1 + C2 J(-eta_h)),
  a local zeta = zeta_L + (3/5) f_NL zeta_L^2 rescaled by lambda has f_NL -> f_NL/lambda:
      T_fNL(eta_h, k) = 1/lambda = [1 + r(1 - rho)] / (1 + 2 r),
      rho(eta_h) = |J(-eta_h)|/I_inf in (0, 1],
  whose |r| >> 1 limit is the purely background quantity
      T_fNL -> (1 - rho(eta_h))/2,        so   0 < T_fNL <= 1/2.
  This is the LINEAR-TRANSFER term.  It does NOT include the bounce's own cubic
  (in-in) contribution generated by the third-order action during NEC violation;
  that term is discussed, with its two published determinations, in the brief.

INTEGRITY: every number reported is produced by this script.  Nothing is asserted
that is not computed here or explicitly cited as literature.
"""
import json
import os
import time
from datetime import datetime, timezone

import numpy as np
import sympy as sp
from scipy.integrate import solve_ivp, quad, cumulative_trapezoid
from scipy.interpolate import CubicSpline
from scipy.optimize import brentq

HERE = os.path.dirname(os.path.abspath(__file__))
JSON_OUT = os.path.join(HERE, "a2_transmission_linear.json")
LOG_OUT = os.path.join(HERE, "a2_transmission_linear.log")

np.random.seed(20260902)   # determinism (no stochastic step is used)
_t0 = time.time()


def log(m):
    line = f"[{time.time()-_t0:7.2f}s] {m}"
    print(line, flush=True)
    with open(LOG_OUT, "a") as f:
        f.write(line + "\n")


# =====================================================================
# [S] SYMBOLIC: branch basis, vacuum decomposition, transfer ratio r
# =====================================================================
def symbolic_block():
    u = sp.symbols("u", positive=True)
    S = sp.sin(u) / u - sp.cos(u)
    C = sp.cos(u) / u + sp.sin(u)
    resS = sp.simplify(sp.diff(S, u, 2) + (1 - 2 / u**2) * S)
    resC = sp.simplify(sp.diff(C, u, 2) + (1 - 2 / u**2) * C)
    S_lead = sp.simplify(sp.series(S, u, 0, 3).removeO())    # ~ u^2/3 -> zeta const
    C_lead = sp.simplify(sp.series(C, u, 0, 2).removeO())    # ~ 1/u   -> zeta ~ tau^-3
    # identity [S1]: e^{-iu}(1 - i/u) + S + i C == 0
    ident_expr = sp.exp(-sp.I * u) * (1 - sp.I / u) + S + sp.I * C
    ident = sp.simplify(sp.expand(ident_expr.rewrite(sp.cos)))
    W = sp.simplify(S * sp.diff(C, u) - sp.diff(S, u) * C)
    A, k, Iinf, rho = sp.symbols("A k I_inf rho", positive=True)
    alpha_m = -k**2 / (3 * A * sp.sqrt(2 * k))
    beta_m = sp.I * 3 * A / (k * sp.sqrt(2 * k))
    r = sp.simplify(beta_m * Iinf / alpha_m)                 # = -9 i A^2 I_inf/k^3
    rr = sp.symbols("r")
    T = (1 + rr * (1 - rho)) / (1 + 2 * rr)
    T_lim = sp.simplify(sp.limit(T, rr, sp.oo))
    return {
        "S_solves_matter_eq": bool(resS == 0),
        "C_solves_matter_eq": bool(resC == 0),
        "S_small_u": str(S_lead),
        "C_small_u": str(C_lead),
        "identity_expmiu_eq_minusS_minusiC": bool(ident == 0),
        "wronskian_S_C": str(W),
        "alpha_minus": str(alpha_m),
        "beta_minus": str(beta_m),
        "r_beta_Iinf_over_alpha": str(r),
        "T_fNL_exact": "(1 + r(1 - rho))/(1 + 2 r)",
        "T_fNL_large_r_limit": str(T_lim),
        "note": ("the adiabatic vacuum in matter contraction is GROWING-branch dominated, "
                 "|r| = 9 A^2 I_inf/k^3 >> 1 for k eta_B << 1; hence T_fNL -> (1-rho)/2 "
                 "and 0 < T_fNL <= 1/2 for ANY bounce of this class"),
    }


# =====================================================================
# [B] BACKGROUNDS
# =====================================================================
def _finalize(eta, a, appa, Hdot, J, label, params):
    """eta, a, appa, Hdot, J given on the full line (J(0) = 0). Derive eta_B,
    I_inf, matter fit A/eta_off."""
    I_inf = float(J[-1])
    # eta_B: first zero of Hdot at eta > 0 (edge of the NEC-violation window)
    sH = CubicSpline(eta, Hdot)
    ib = int(np.argmin(np.abs(eta)))
    i = ib
    while i + 1 < len(eta) and Hdot[i + 1] > 0:
        i += 1
    eta_B = float(brentq(sH, eta[i], eta[i + 1])) if i + 1 < len(eta) else float(eta[-1])
    # matter fit: sqrt(a) linear in eta over the far tail (a > 0.3 a_max)
    m = a > 0.3 * a[-1]
    m &= eta > 0
    e_t, s_t = eta[m], np.sqrt(a[m])
    slope, icept = np.polyfit(e_t, s_t, 1)
    A = float(slope**2)
    eta_off = float(-icept / slope)
    sJ = CubicSpline(eta, J)
    # Weinberg gradient-expansion O(k^2) correction to the constant branch:
    #   zeta_C(eta) = 1 + k^2 f1(eta) + O(k^4),
    #   F(eta) = int_0^eta a^2 deta',   f1(eta) = -int_0^eta F/a^2 deta'
    F = np.concatenate([[0.0], cumulative_trapezoid(a**2, eta)])
    F = F - float(np.interp(0.0, eta, F))
    f1 = np.concatenate([[0.0], cumulative_trapezoid(-F / a**2, eta)])
    f1 = f1 - float(np.interp(0.0, eta, f1))
    return {"label": label, "params": params, "eta": eta, "a": a, "appa": appa,
            "J": J, "Jf": sJ, "I_inf": I_inf, "eta_B": eta_B, "A": A, "eta_off": eta_off,
            "J_at_minus_etaB": float(sJ(-eta_B)), "eta_far": float(eta[-1]),
            "matter_fit_npts": int(m.sum()),
            "af": CubicSpline(eta, a), "f1f": CubicSpline(eta, f1),
            "Ff": CubicSpline(eta, F)}


def _mirror(eta_h, a_h, appa_h, Hd_h, J_h):
    eta = np.concatenate([-eta_h[::-1][:-1], eta_h])
    a = np.concatenate([a_h[::-1][:-1], a_h])
    appa = np.concatenate([appa_h[::-1][:-1], appa_h])
    Hd = np.concatenate([Hd_h[::-1][:-1], Hd_h])
    J = np.concatenate([-J_h[::-1][:-1], J_h])
    return eta, a, appa, Hd, J


def bg_lqc(x_min=1e-12, N1=200001, N2=200001, x_split=0.1):
    """(i) LQC effective quasi-dust bounce, H^2 = (rho/3)(1 - rho/rho_c), w = 0.
    Two-piece parametrization: s = sqrt(1-x) through the bounce (regular, no
    regulator), y = ln x through the matter tail (resolves a -> inf)."""
    # piece A: bounce region x in [x_split, 1]
    s1 = np.sqrt(1.0 - x_split)
    s = np.linspace(0.0, s1, N1)
    xA = 1.0 - s**2
    detaA = 2.0 / (np.sqrt(3.0) * (1.0 - s**2) ** (7.0 / 6.0))
    dJA = 2.0 / (np.sqrt(3.0) * np.sqrt(1.0 - s**2))
    etaA = np.concatenate([[0.0], cumulative_trapezoid(detaA, s)])
    JA = np.concatenate([[0.0], cumulative_trapezoid(dJA, s)])
    # piece B: matter tail x in [x_min, x_split], y = ln x descending
    y = np.linspace(np.log(x_split), np.log(x_min), N2)
    xB = np.exp(y)
    detaB = -xB ** (-1.0 / 6.0) / (np.sqrt(3.0) * np.sqrt(1.0 - xB))
    dJB = -np.sqrt(xB) / (np.sqrt(3.0) * np.sqrt(1.0 - xB))
    etaB_ = etaA[-1] + np.concatenate([[0.0], cumulative_trapezoid(detaB, y)])
    JB_ = JA[-1] + np.concatenate([[0.0], cumulative_trapezoid(dJB, y)])
    x = np.concatenate([xA, xB[1:]])
    eta_h = np.concatenate([etaA, etaB_[1:]])
    J_h = np.concatenate([JA, JB_[1:]])
    a_h = x ** (-1.0 / 3.0)
    appa_h = x ** (1.0 / 3.0) * (1.0 / 6.0 + x / 3.0)   # a''/a, phase-2 result
    Hd_h = -0.5 * x * (1.0 - 2.0 * x)                   # LQC Hdot; > 0 for x > 1/2
    return _finalize(*_mirror(eta_h, a_h, appa_h, Hd_h, J_h),
                     "LQC-effective-dust", {"rho_c": 1.0, "w": 0.0, "x_min": x_min})


def bg_poly(eta_b=1.0, u_far=4000.0, N=400001):
    """(ii) analytic non-LQC bounce a(eta) = a_b (1 + eta^2/eta_b^2), a_b = 1.
    Everything closed form: a''/a = 2/(eta^2+eta_b^2); J = (eta_b/2)[atan u + u/(1+u^2)];
    I_inf = pi eta_b/4; Hdot = 0 at u = 1/sqrt(3)."""
    u = np.linspace(-u_far, u_far, N)
    eta = u * eta_b
    a = 1.0 + u**2
    appa = 2.0 / (eta_b**2 * (1.0 + u**2))
    Hd = (2.0 / eta_b**2) * (1.0 - 3.0 * u**2) / (1.0 + u**2) ** 4
    J = 0.5 * eta_b * (np.arctan(u) + u / (1.0 + u**2))
    return _finalize(eta, a, appa, Hd, J, "poly-analytic-nonLQC",
                     {"eta_b": eta_b, "a_b": 1.0})


def bg_quintin(dtB=1.0, t_far=1.0e6, N=400001):
    """(iii) Quintin, Sherkatghanad, Cai & Brandenberger 2015 (arXiv:1508.04141):
    bounce phase H(t) = Upsilon (t - t_B), a = a_B exp(Upsilon (t-t_B)^2/2),
    matched to matter contraction/expansion at the NEC boundary |t - t_B| = dtB/2.
    Matching H fixes Upsilon = 8/(3 dtB^2); a_B = 1, t_B = 0."""
    Ups = 8.0 / (3.0 * dtB**2)
    tm = dtB / 2.0
    aB = 1.0
    a_m = aB * np.exp(Ups * tm**2 / 2.0)
    n_in, n_out = N // 2, N // 2
    t_in = np.linspace(0.0, tm, n_in)
    t_out = tm * np.exp(np.linspace(0.0, np.log(t_far / tm), n_out))[1:]
    t = np.concatenate([t_in, t_out])
    inb = t <= tm
    a = np.where(inb, aB * np.exp(Ups * np.minimum(t, tm) ** 2 / 2.0),
                 a_m * (np.maximum(t, tm) / tm) ** (2.0 / 3.0))
    H = np.where(inb, Ups * t, (2.0 / 3.0) / np.maximum(t, tm))
    Hd = np.where(inb, Ups, -1.5 * H**2)
    eta_h = np.concatenate([[0.0], cumulative_trapezoid(1.0 / a, t)])
    J_h = np.concatenate([[0.0], cumulative_trapezoid(1.0 / a**3, t)])
    appa_h = a**2 * (2.0 * H**2 + Hd)
    return _finalize(*_mirror(eta_h, a, appa_h, Hd, J_h),
                     "Quintin2015-type", {"dtB": dtB, "Upsilon": Ups, "a_B": aB,
                                          "t_far": t_far})


# =====================================================================
# [M] mode evolution + exact matter-basis projection
# =====================================================================
def _matter_basis(k, tau):
    u = k * tau
    S = np.sin(u) / u - np.cos(u)
    C = np.cos(u) / u + np.sin(u)
    dS = k * (np.cos(u) / u - np.sin(u) / u**2 + np.sin(u))
    dC = k * (-np.sin(u) / u - np.cos(u) / u**2 + np.cos(u))
    return S, C, dS, dC


def project(bg, k, eta_m, mu, dmu):
    """(mu, mu') -> (alpha, beta) in the normalisation zeta_C -> 1,
    zeta_G -> -1/(3 A^2 tau^3)  (so mu_G = -1/(3 A tau));
    alpha = C1 -+ C2 I_inf (pre/post), beta = C2."""
    A, off = bg["A"], bg["eta_off"]
    tau = eta_m - off
    S, C, dS, dC = _matter_basis(k, tau)
    mC, dmC = (3 * A / k**2) * S, (3 * A / k**2) * dS
    mG, dmG = -(k / (3 * A)) * C, -(k / (3 * A)) * dC
    W = mC * dmG - dmC * mG
    return (mu * dmG - dmu * mG) / W, (mC * dmu - dmC * mu) / W


def _rhs_factory(spl, k):
    def rhs(e, y):
        w = spl(e)
        return [y[1], -(k * k - w) * y[0], y[3], -(k * k - w) * y[2]]
    return rhs


def evolve(bg, k, eta_far, ic="vacuum", rtol=1e-11, atol=1e-14):
    spl = CubicSpline(bg["eta"], bg["appa"])
    off = bg["eta_off"]
    e_i, e_f = -eta_far, eta_far
    tau_i = e_i - off
    if ic == "vacuum":
        u = k * tau_i
        mu0 = np.exp(-1j * u) * (1 - 1j / u) / np.sqrt(2 * k)
        dmu0 = (np.exp(-1j * u) * (-1j * k) * (1 - 1j / u)
                + np.exp(-1j * u) * (1j / (k * tau_i**2))) / np.sqrt(2 * k)
    else:
        raise ValueError(ic)
    sol = solve_ivp(_rhs_factory(spl, k), [e_i, e_f],
                    [mu0.real, dmu0.real, mu0.imag, dmu0.imag],
                    rtol=rtol, atol=atol, method="DOP853", dense_output=True)
    yf = sol.y[:, -1]
    mu_f, dmu_f = yf[0] + 1j * yf[2], yf[1] + 1j * yf[3]
    a_m, b_m = project(bg, k, e_i, mu0, dmu0)
    a_p, b_p = project(bg, k, e_f, mu_f, dmu_f)
    return {"alpha_pre": a_m, "beta_pre": b_m, "alpha_post": a_p, "beta_post": b_p,
            "sol": sol, "eta_i": e_i, "eta_f": e_f, "success": bool(sol.success)}


def constant_branch_transmission(bg, k, u_out=0.2, rtol=1e-12, atol=1e-16):
    r"""Independent reproduction of the phase-3 result T_c(k) = 1.

    At k = 0 the EXACT constant-zeta solution of mu'' = (a''/a) mu is mu = a(eta)
    (zeta = mu/a = 1), for ANY background.  Impose that as the IC at a symmetric
    super-Hubble epoch -eta_out (k eta_out = u_out << 1), integrate the full
    finite-k equation through the bounce, and read zeta = mu/a at +eta_out.
    T_c = zeta(+eta_out)/zeta(-eta_out); any deviation from 1 is the physical
    O((k eta_out)^2) gradient correction plus numerics -- NOT the matter-asymptote
    IC mismatch that contaminates a projected-basis version of this test.
    """
    eta_out = u_out / k
    if eta_out > 0.9 * bg["eta_far"] or eta_out < 3.0 * bg["eta_B"]:
        return None
    spl = CubicSpline(bg["eta"], bg["appa"])
    spa, sf1, sF = bg["af"], bg["f1f"], bg["Ff"]
    # constant branch prepared to O(k^4): zeta_C = 1 + k^2 f1, mu = a zeta_C
    e0 = -eta_out
    a0, ap0 = float(spa(e0)), float(spa.derivative()(e0))
    z0 = 1.0 + k * k * float(sf1(e0))
    dz0 = k * k * (-float(sF(e0)) / a0**2)          # f1' = -F/a^2
    mu0, dmu0 = a0 * z0, ap0 * z0 + a0 * dz0

    def rhs(e, y):
        return [y[1], -(k * k - spl(e)) * y[0]]

    sol = solve_ivp(rhs, [e0, eta_out], [mu0, dmu0], rtol=rtol, atol=atol, method="DOP853")
    z_out = sol.y[0, -1] / float(spa(eta_out))
    z_ref = 1.0 + k * k * float(sf1(eta_out))       # zeta_C(+eta_out) (f1 even by parity)
    Tc = z_out / z_ref
    return {"k": float(k), "k_etaB": float(k * bg["eta_B"]), "eta_out": float(eta_out),
            "eta_out_over_etaB": float(eta_out / bg["eta_B"]), "u_out": float(u_out),
            "k2_f1_correction": float(k * k * float(sf1(eta_out))),
            "T_c": float(Tc), "abs_T_c_minus_1": float(abs(Tc - 1.0))}


def zeta_at(bg, ev, eta_q):
    """zeta = mu/a from the dense ODE solution."""
    y = ev["sol"].sol(eta_q)
    mu = y[0] + 1j * y[2]
    return mu / np.interp(eta_q, bg["eta"], bg["a"])


# =====================================================================
# [T] transmission coefficient
# =====================================================================
def T_fNL_background(bg, eta_h):
    """large-|r| (background-only) value: T = (1 - rho)/2."""
    rho = abs(float(bg["Jf"](-eta_h))) / bg["I_inf"]
    return rho, 0.5 * (1.0 - rho)


def T_fNL_exact(bg, k, eta_h, ev):
    """exact finite-k value from the projected vacuum coefficients."""
    am, bm = ev["alpha_pre"], ev["beta_pre"]
    C1, C2 = am + bm * bg["I_inf"], bm
    Jh = float(bg["Jf"](-eta_h))
    lam = (C1 + C2 * bg["I_inf"]) / (C1 + C2 * Jh)
    return 1.0 / lam


# =====================================================================
# [F] effective-fluid scheme contrast (LQC background; p = 0, c_s = 1)
# =====================================================================
def fluid_scheme_contrast(dcuts=(1e-5, 1e-6, 1e-7, 1e-8), x_lo=0.5):
    """K = int z^2 deta over the near-bounce window [x_lo, 1-dcut].
    z^2 = 3 x^{-2/3}/(1-x); deta = dx/(sqrt3 x^{7/6} sqrt(1-x))
    => integrand = sqrt3 x^{-11/6} (1-x)^{-3/2}  -> K ~ dcut^{-1/2}."""
    rows = []
    # substitute x = 1 - w^2 (regularises the (1-x)^{-3/2} endpoint):
    #   K  = int 2 sqrt3 (1-w^2)^{-11/6} w^{-2} dw,   w in [sqrt(dcut), sqrt(1-x_lo)]
    #   Im = int deta/z^2 = int (2/(3 sqrt3)) (1-w^2)^{-1/6} dw   (finite as w -> 0)
    for dc in dcuts:
        f = lambda w: 2.0 * np.sqrt(3.0) * (1.0 - w**2) ** (-11.0 / 6.0) / w**2
        K, _ = quad(f, np.sqrt(dc), np.sqrt(1.0 - x_lo), limit=500)
        g = lambda w: (2.0 / (3.0 * np.sqrt(3.0))) * (1.0 - w**2) ** (-1.0 / 6.0)
        Im, _ = quad(g, np.sqrt(dc), np.sqrt(1.0 - x_lo), limit=500)
        rows.append({"dcut": dc, "K_fluid_near_bounce": float(K),
                     "Imix_fluid_near_bounce": float(Im)})
    p = float(np.polyfit(np.log10([r["dcut"] for r in rows]),
                         np.log10([r["K_fluid_near_bounce"] for r in rows]), 1)[0])
    # SECOND SCHEME's transmission coefficient, LQC dust background.
    #   z^2 = 3 x^{-2/3}/(1-x);  deta/z^2 = -dx sqrt(1-x)/(3 sqrt3 sqrt x)
    #   => J_f(x) = int_x^1 sqrt(1-x')/(3 sqrt3 sqrt x') dx',  I_f = pi/(6 sqrt3)
    # In the matter limit z -> sqrt3 a, so z is proportional to a and the vacuum
    # branch decomposition (|r| >> 1) carries over unchanged; only rho changes.
    jf = lambda xx: np.sqrt(1.0 - xx) / (3.0 * np.sqrt(3.0) * np.sqrt(xx))
    I_f, _ = quad(jf, 0.0, 1.0, limit=400)
    J_f_at_half, _ = quad(jf, 0.5, 1.0, limit=400)
    rho_f = J_f_at_half / I_f
    fluid_T = {
        "background": "LQC-effective-dust", "scheme": "effective fluid z^2 = a^2(rho+p)/(c_s^2 H^2)",
        "I_inf_fluid": float(I_f), "I_inf_fluid_analytic_pi_over_6sqrt3": float(np.pi / (6 * np.sqrt(3.0))),
        "J_fluid_at_NEC_boundary_x_eq_half": float(J_f_at_half),
        "rho_B_fluid": float(rho_f), "T_fNL_fluid": float(0.5 * (1.0 - rho_f)),
        "T_fNL_geometric_same_background": 0.25,
        "note": ("the MIXING integral int deta/z^2 is finite in the fluid scheme too, so a "
                 "transmission coefficient exists there and is reported; it differs from the "
                 "geometric-prescription value on the SAME background, which is the "
                 "scheme dependence the ledger row asks to be stated. What does NOT exist in "
                 "the fluid scheme is the finite-k continuation (K diverges), so its "
                 "coefficient is leading-gradient-order only.")}
    return {"rows": rows, "x_lo": x_lo, "fitted_power_of_dcut_for_K": p,
            "SECOND_SCHEME_transmission": fluid_T,
            "analytic_power": -0.5,
            "note": ("effective-fluid scheme: the k^2 gradient-basis integral "
                     "K = int z^2 deta DIVERGES as dcut^{-1/2} at the H = 0 pole, so the "
                     "finite-k continuation of the constant branch does not exist there "
                     "(phase-1's 'no scheme-independent coefficient'). The geometric "
                     "prescription z = a has both basis integrals finite. Note the MIXING "
                     "integral int deta/z^2 is finite in BOTH schemes, so the transmission "
                     "coefficient computed here is a fluid-scheme quantity as well, with a "
                     "different numerical value (reported)." )}


def main():
    open(LOG_OUT, "w").close()
    log("=" * 78)
    log("TRACK A2 -- f_NL transmission through explicit nonsingular bounces")
    log("=" * 78)

    log("[S] symbolic branch basis + vacuum decomposition ...")
    S = symbolic_block()
    for kk in ("S_solves_matter_eq", "C_solves_matter_eq",
               "identity_expmiu_eq_minusS_minusiC"):
        log(f"    {kk}: {S[kk]}")
    log(f"    alpha_- = {S['alpha_minus']} ; beta_- = {S['beta_minus']}")
    log(f"    r = {S['r_beta_Iinf_over_alpha']} ; T_fNL -> {S['T_fNL_large_r_limit']}")

    log("[B] building backgrounds ...")
    bgs = {"LQC": bg_lqc(), "poly": bg_poly(eta_b=1.0), "quintin": bg_quintin(dtB=1.0)}
    # analytic cross-checks
    an = {
        "LQC": {"I_inf": float(np.pi / np.sqrt(3.0)), "A": 1.0 / 12.0,
                "rho_B": 0.5,
                "src": "I_inf = int_0^1 dx/(sqrt3 sqrt(x(1-x))) = pi/sqrt3 ; "
                       "a = (eta-eta_off)^2/12 in the dust era ; "
                       "Hdot = 0 at x = 1/2 and 2 arcsin(sqrt x)|_{1/2}^{1} / (pi) = 1/2"},
        "poly": {"I_inf": float(np.pi / 4.0), "A": 1.0,
                 "rho_B": float((np.arctan(1 / np.sqrt(3.0)) + (1 / np.sqrt(3.0)) / (4.0 / 3.0))
                                / (np.pi / 2.0)),
                 "src": "I_inf = pi eta_b/4 ; A = a_b/eta_b^2 ; Hdot = 0 at u = 1/sqrt3"},
    }
    bmeta = {}
    for key, b in bgs.items():
        rho_B = abs(b["J_at_minus_etaB"]) / b["I_inf"]
        bmeta[key] = {"label": b["label"], "params": b["params"], "eta_B": b["eta_B"],
                      "I_inf": b["I_inf"], "A": b["A"], "eta_off": b["eta_off"],
                      "J_at_minus_etaB": b["J_at_minus_etaB"], "rho_B": float(rho_B),
                      "eta_far_grid": b["eta_far"], "matter_fit_npts": b["matter_fit_npts"]}
        if key in an:
            bmeta[key]["analytic_check"] = {
                "I_inf_analytic": an[key]["I_inf"],
                "I_inf_relerr": float(abs(b["I_inf"] / an[key]["I_inf"] - 1)),
                "A_analytic": an[key]["A"],
                "A_relerr": float(abs(b["A"] / an[key]["A"] - 1)),
                "rho_B_analytic": an[key]["rho_B"],
                "rho_B_relerr": float(abs(rho_B / an[key]["rho_B"] - 1)),
                "derivation": an[key]["src"]}
        log(f"    {key:8s} eta_B={b['eta_B']:.6g} I_inf={b['I_inf']:.8g} A={b['A']:.8g} "
            f"eta_off={b['eta_off']:.6g} rho_B={rho_B:.8f}")
        if key in an:
            c = bmeta[key]["analytic_check"]
            log(f"    {key:8s} analytic: I_inf {c['I_inf_relerr']:.2e}, "
                f"A {c['A_relerr']:.2e}, rho_B {c['rho_B_relerr']:.2e} (rel. err)")

    log("[M] mode-evolution verification ...")
    ks = [2e-3, 5e-3, 1e-2, 2e-2, 3e-2]
    verif, evs = {}, {}
    for key in ("poly", "LQC", "quintin"):
        b = bgs[key]
        eta_far = min(0.9 * b["eta_far"], 400.0 * b["eta_B"])
        rows = []
        evs[key] = {}
        # (a) pure constant-branch IC -> the clean T_c test
        for kt in ks:
            k = kt / b["eta_B"]
            cbt = constant_branch_transmission(b, k)
            # (b) physical adiabatic-vacuum IC
            ev = evolve(b, k, eta_far, ic="vacuum")
            evs[key][kt] = ev
            am, bm = ev["alpha_pre"], ev["beta_pre"]
            r_num = bm * b["I_inf"] / am
            r_pred = -9j * b["A"] ** 2 * b["I_inf"] / k**3
            # direct check: zeta at the NEC boundary (super-Hubble, from the dense ODE
            # solution) divided by the exact post-bounce super-Hubble constant alpha_post
            # (projected on the exact matter basis, so it is immune to the post-bounce
            #  horizon re-entry that makes zeta(eta_far) oscillate for the larger k)
            z_h = zeta_at(b, ev, -b["eta_B"])
            T_direct = z_h / ev["alpha_post"]
            T_proj = T_fNL_exact(b, k, b["eta_B"], ev)
            rho_B, T_bg = T_fNL_background(b, b["eta_B"])
            rows.append({
                "k_etaB": float(kt), "k": float(k),
                "T_c_constant_branch": cbt,
                "T_c_constant_branch_abs_minus_1": (cbt["abs_T_c_minus_1"] if cbt else None),
                "abs_r_numeric": float(abs(r_num)),
                "r_relerr_vs_closed_form": float(abs(r_num - r_pred) / abs(r_pred)),
                "T_fNL_direct_zeta_ratio_re": float(T_direct.real),
                "T_fNL_direct_zeta_ratio_im": float(T_direct.imag),
                "T_fNL_projected_exact_re": float(np.real(T_proj)),
                "T_fNL_background_limit": float(T_bg),
                "direct_vs_background_relerr": float(abs(T_direct.real / T_bg - 1)),
                "Delta2_out_arbunits": float(k**3 * abs(ev["alpha_post"]) ** 2),
            })
            _tc = rows[-1]['T_c_constant_branch_abs_minus_1']
            log(f"    {key:8s} k*etaB={kt:.4g} |T_c-1|={('%.2e' % _tc) if _tc is not None else 'n/a':>8s} "
                f"|r|={rows[-1]['abs_r_numeric']:.3e} (rel {rows[-1]['r_relerr_vs_closed_form']:.2e}) "
                f"T_fNL_direct={T_direct.real:+.6f} (bg {T_bg:+.6f}, "
                f"rel {rows[-1]['direct_vs_background_relerr']:.2e})")
        d2 = np.array([r["Delta2_out_arbunits"] for r in rows])
        verif[key] = {
            "rows": rows,
            "max_abs_T_c_minus_1": float(max([r["T_c_constant_branch_abs_minus_1"] for r in rows
                                              if r["T_c_constant_branch_abs_minus_1"] is not None] or [np.nan])),
            "max_T_fNL_direct_vs_background_relerr":
                float(max(r["direct_vs_background_relerr"] for r in rows)),
            "Delta2_out_spread_frac": float((d2.max() - d2.min()) / d2.mean()),
            "note": ("T_c(k) = 1 confirmed with a PURE constant-branch IC (phase-3 result, "
                     "independently reproduced in three backgrounds); the physical vacuum is "
                     "growing-branch dominated (|r| >> 1) and its transmission is NOT unity. "
                     "Delta^2 = k^3|alpha_post|^2 flat across k => post-bounce spectrum scale "
                     "invariant (matter-bounce benchmark recovered)."),
        }
        log(f"    {key:8s} max|T_c-1|={verif[key]['max_abs_T_c_minus_1']:.2e}  "
            f"Delta^2 spread={verif[key]['Delta2_out_spread_frac']:.2e}")

    log("[T] transmission coefficient T_fNL(handoff epoch) ...")
    T = {}
    for key, b in bgs.items():
        eB = b["eta_B"]
        rows = []
        for name, eh in [("NEC boundary (eta_h = eta_B)", eB), ("2 eta_B", 2 * eB),
                         ("5 eta_B", 5 * eB), ("10 eta_B", 10 * eB), ("50 eta_B", 50 * eB)]:
            rho, Tb = T_fNL_background(b, eh)
            rows.append({"handoff": name, "eta_h": float(eh),
                         "eta_h_over_etaB": float(eh / eB), "rho": float(rho),
                         "lambda_zeta": float(2.0 / (1.0 - rho)), "T_fNL": float(Tb)})
            log(f"    {key:8s} {rows[-1]['handoff']:28s} rho={rho:.6f} "
                f"lambda={rows[-1]['lambda_zeta']:8.4f} T_fNL={Tb:+.6f}")
        T[key] = rows

    log("[Q] bounce-duration sweeps (self-similarity test) ...")
    qsweep, psweep = [], []
    for dtB in [0.25, 0.5, 1.0, 2.0, 4.0]:
        b = bg_quintin(dtB=dtB, N=200001)
        rho, Tb = T_fNL_background(b, b["eta_B"])
        qsweep.append({"dtB": dtB, "Upsilon": b["params"]["Upsilon"], "eta_B": b["eta_B"],
                       "I_inf": b["I_inf"], "rho_B": float(rho), "T_fNL": float(Tb)})
        log(f"    quintin dtB={dtB:<5g} eta_B={b['eta_B']:.6g} I_inf={b['I_inf']:.6g} "
            f"rho_B={rho:.8f} T_fNL={Tb:+.8f}")
    for eb in [0.25, 0.5, 1.0, 2.0, 4.0]:
        b = bg_poly(eta_b=eb, N=200001)
        rho, Tb = T_fNL_background(b, b["eta_B"])
        psweep.append({"eta_b": eb, "eta_B": b["eta_B"], "eta_B_over_eta_b": b["eta_B"] / eb,
                       "I_inf": b["I_inf"], "rho_B": float(rho), "T_fNL": float(Tb)})
        log(f"    poly    eta_b={eb:<5g} eta_B={b['eta_B']:.6g} I_inf={b['I_inf']:.6g} "
            f"rho_B={rho:.8f} T_fNL={Tb:+.8f}")
    q_spread = float(np.ptp([r["T_fNL"] for r in qsweep]) / np.mean([r["T_fNL"] for r in qsweep]))
    p_spread = float(np.ptp([r["T_fNL"] for r in psweep]) / np.mean([r["T_fNL"] for r in psweep]))
    log(f"    duration dependence: quintin frac-spread {q_spread:.2e}, poly {p_spread:.2e} "
        f"-> T_fNL is DURATION-INDEPENDENT within each self-similar family")

    log("[F] effective-fluid scheme contrast ...")
    F = fluid_scheme_contrast()
    log(f"    K_fluid ~ dcut^{F['fitted_power_of_dcut_for_K']:.4f} (analytic -0.5)")
    ft = F["SECOND_SCHEME_transmission"]
    log(f"    SECOND SCHEME (effective fluid, LQC bg): I_inf={ft['I_inf_fluid']:.6f} "
        f"rho_B={ft['rho_B_fluid']:.6f} T_fNL={ft['T_fNL_fluid']:.6f} "
        f"(geometric on same bg: {ft['T_fNL_geometric_same_background']:.6f})")

    log("[C] convergence checks ...")
    b = bgs["poly"]
    k = 1e-2 / b["eta_B"]
    base = evolve(b, k, 400.0 * b["eta_B"], ic="vacuum")
    conv = {}
    for tag, kw in [("eta_far_x2", dict(eta_far=800.0 * b["eta_B"])),
                    ("rtol_1e-9", dict(eta_far=400.0 * b["eta_B"], rtol=1e-9, atol=1e-12))]:
        alt = evolve(b, k, ic="vacuum", **kw)
        conv[tag] = float(abs(T_fNL_exact(b, k, b["eta_B"], alt)
                              / T_fNL_exact(b, k, b["eta_B"], base) - 1))
        log(f"    {tag}: dT_fNL/T = {conv[tag]:.3e}")
    for key, half in [("LQC", bg_lqc(N1=100001, N2=100001)),
                      ("poly", bg_poly(eta_b=1.0, N=200001)),
                      ("quintin", bg_quintin(dtB=1.0, N=200001))]:
        r0, T0 = T_fNL_background(bgs[key], bgs[key]["eta_B"])
        r1, T1 = T_fNL_background(half, half["eta_B"])
        conv[f"grid_halved_{key}_dT_rel"] = float(abs(T1 / T0 - 1))
        log(f"    grid halved {key}: dT_fNL/T = {conv[f'grid_halved_{key}_dT_rel']:.3e}")
    b_deep = bg_lqc(x_min=1e-14, N1=200001, N2=200001)
    _, T_deep = T_fNL_background(b_deep, b_deep["eta_B"])
    _, T_std = T_fNL_background(bgs["LQC"], bgs["LQC"]["eta_B"])
    conv["LQC_xmin_1e-14_dT_rel"] = float(abs(T_deep / T_std - 1))
    log(f"    LQC x_min 1e-12 -> 1e-14: dT_fNL/T = {conv['LQC_xmin_1e-14_dT_rel']:.3e}")

    fnl_pre = -35.0 / 16.0
    headline = {}
    for key, b in bgs.items():
        rB = T[key][0]
        kk = 1e-2
        row = [r for r in verif[key]["rows"] if r["k_etaB"] == kk][0]
        headline[key] = {
            "scheme": "geometric / dressed-metric prescription z = a, c_s = 1",
            "background": b["label"], "eta_B": b["eta_B"], "I_inf": b["I_inf"],
            "rho_B": rB["rho"],
            "T_fNL_linear_transfer": rB["T_fNL"],
            "T_fNL_direct_ODE_check_at_kEtaB_0p01": row["T_fNL_direct_zeta_ratio_re"],
            "zeta_amplification_lambda": rB["lambda_zeta"],
            "f_NL_after_from_minus_35_over_16": fnl_pre * rB["T_fNL"],
        }
        log(f"  HEADLINE {key:8s}: T_fNL = {rB['T_fNL']:.6f}  (lambda_zeta = "
            f"{rB['lambda_zeta']:.4f})  =>  f_NL: {fnl_pre:+.4f} -> "
            f"{fnl_pre*rB['T_fNL']:+.4f}   [LINEAR-TRANSFER TERM ONLY]")
    Ts = [headline[k2]["T_fNL_linear_transfer"] for k2 in headline]
    log(f"  SCHEME/BACKGROUND SPREAD: T_fNL in [{min(Ts):.4f}, {max(Ts):.4f}] "
        f"(+/-{100*(max(Ts)-min(Ts))/(max(Ts)+min(Ts)):.1f}%)")

    out = {
        "track": "A2 -- transmission of f_NL through an explicit nonsingular bounce",
        "ledger_row": "NEXT_SCIENCE_LEDGER.md item #2",
        "meta": {"date_utc": datetime.now(timezone.utc).isoformat(),
                 "runtime_s": round(time.time() - _t0, 2),
                 "numpy": np.__version__, "scipy_solver": "DOP853", "sympy": sp.__version__,
                 "seed": 20260902, "f_NL_contraction_input": fnl_pre},
        "S_symbolic": S,
        "B_backgrounds": bmeta,
        "M_mode_evolution_verification": verif,
        "T_transmission_tables": T,
        "Q_quintin_duration_sweep": qsweep,
        "Q_quintin_duration_frac_spread": q_spread,
        "Qp_poly_duration_sweep": psweep,
        "Qp_poly_duration_frac_spread": p_spread,
        "F_fluid_scheme_contrast": F,
        "C_convergence": conv,
        "HEADLINE": headline,
        "HEADLINE_scheme_spread": {"min": float(min(Ts)), "max": float(max(Ts))},
        "validity": {
            "domain": ("super-Hubble (k eta_B << 1), linear-order transfer of the curvature "
                       "perturbation, single-clock adiabatic matter contraction with a > 0 "
                       "throughout, geometric prescription z = a (c_s = 1), symmetric or "
                       "matched bounce with bounded a''/a."),
            "computed": ("(a) T_c(k) = 1 for a pure constant-branch IC (phase-3 reproduced in "
                         "three backgrounds); (b) the adiabatic vacuum is growing-branch "
                         "dominated, |r| = 9 A^2 I_inf/k^3; (c) the k-independent super-Hubble "
                         "rescaling lambda between the NEC boundary and late times, hence the "
                         "LINEAR-TRANSFER transmission coefficient T_fNL = 1/lambda = "
                         "(1 - rho_B)/2 with rho_B = |J(-eta_B)|/I_inf."),
            "NOT_computed": ("the bounce's OWN cubic (in-in) contribution Delta f_NL^bounce from "
                             "the third-order action during NEC violation. Quintin et al. 2015 "
                             "(arXiv:1508.04141) find f_NL is ENHANCED during the bounce phase "
                             "when zeta grows; Agullo, Bolliet & Sreenath 2017 (arXiv:1712.08148) "
                             "find the LQC bounce enhances non-Gaussianity by several orders of "
                             "magnitude on scales larger than the curvature radius at the bounce. "
                             "That term has the OPPOSITE sign of effect to the suppression "
                             "computed here and is NOT bounded by it: the net T_fNL is therefore "
                             "NOT determined by the linear transfer alone."),
        },
    }
    with open(JSON_OUT, "w") as f:
        json.dump(out, f, indent=2)
    log(f"DONE ({time.time()-_t0:.1f} s) -> {JSON_OUT}")


if __name__ == "__main__":
    main()
