#!/usr/bin/env node
/**
 * Seed `paper_figures` rows for the 6 bigbounce papers by parsing each
 * paper's current .tex file for \includegraphics{...} and the surrounding
 * \caption{...} + \label{...} blocks.
 *
 * For each figure:
 *   1. Pull the basename from \includegraphics
 *   2. Resolve a public asset path under site/public/ (probes a list of
 *      known mirror locations; falls back to the paper-local figures/ dir
 *      if a copy lives at site/public/images/<basename>.png)
 *   3. Extract the nearest \caption{...} and \label{fig:...} (paren-balanced)
 *   4. Upsert into Convex paper_figures via figures:upsertByOrdinal
 *
 * Stale figures are pruned by calling figures:removeByPaper before each
 * paper's upsert wave, so figures removed from the .tex in a revision
 * round disappear automatically.
 *
 * Idempotent. Safe to re-run.
 */
import { readFileSync, existsSync, copyFileSync, mkdirSync } from "node:fs";
import { resolve, dirname, basename, extname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { ConvexHttpClient } from "convex/browser";
import { api } from "../convex/_generated/api.js";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const REPO = resolve(__dirname, "..");

const CONVEX_URL =
  process.env.CONVEX_URL || "https://brilliant-panther-471.convex.cloud";
const client = new ConvexHttpClient(CONVEX_URL);

// Per-paper config: slug, .tex source, version (read from papers.ts later if
// we want, but the seed records the version-at-time-of-seed inline), and
// the candidate public image roots to probe for each figure file.
const PAPERS = [
  {
    slug: "paper-1a",
    label: "Paper 1A",
    tex: "arxiv/paper1a_ech_nogo.tex",
    publicRoots: [
      "public/images",
      "site/public/images",
      "site/public/arxiv_v2/figures",
      "arxiv/figures",
      "arxiv",
    ],
  },
  {
    slug: "paper-1b",
    label: "Paper 1B",
    tex: "arxiv/paper1b_mcmc_companion.tex",
    publicRoots: [
      "public/images",
      "site/public/images",
      "site/public/arxiv_v2/figures",
      "arxiv/figures",
      "arxiv",
    ],
  },
  {
    slug: "paper-2",
    label: "Paper 2",
    tex: "research/focused_paper_source_integration/02_full_draft.tex",
    publicRoots: [
      "public/images",
      "site/public/images",
      "research/focused_paper_source_integration",
    ],
  },
  {
    slug: "paper-3",
    label: "Paper 3",
    tex: "pipelines/p3_anomaly_engine/paper3_draft.tex",
    publicRoots: [
      "public/images",
      "site/public/images",
      "pipelines/p3_anomaly_engine/figures",
    ],
  },
  {
    slug: "paper-4",
    label: "Paper 4",
    tex: "pipelines/p2_chirality/chirality_catalog_paper.tex",
    publicRoots: [
      "public/images/chirality",
      "public/images",
      "site/public/images/chirality",
      "site/public/images",
      "pipelines/p2_chirality",
    ],
  },
  {
    slug: "paper-5",
    label: "Paper 5",
    tex: "pipelines/p5_desi_chirality/paper/p5_desi_chirality.tex",
    publicRoots: [
      "public/images/p5",
      "public/images",
      "site/public/images",
      "pipelines/p5_desi_chirality/paper",
      "pipelines/p5_desi_chirality/figures",
    ],
  },
];

// Where copies are written if a referenced figure lives only in a
// pipelines/ source dir. The repo-root public/images is canonical;
// site/public/images is regenerated by the predev/prebuild copy step
// (site/scripts/copy-old-site.mjs).
const CANONICAL_PUBLIC_IMAGES = "public/images";

// ──────────────────────────────────────────────────────────────────
// LaTeX-text helpers
// ──────────────────────────────────────────────────────────────────

// Return the substring of `s` starting just after `openIdx` (which must
// point at `{`) that is balanced by matching `{`/`}`. Returns null on
// unbalanced input.
function readBalanced(s, openIdx) {
  if (s[openIdx] !== "{") return null;
  let depth = 0;
  for (let i = openIdx; i < s.length; i++) {
    if (s[i] === "{") depth++;
    else if (s[i] === "}") {
      depth--;
      if (depth === 0) return { content: s.slice(openIdx + 1, i), end: i + 1 };
    }
  }
  return null;
}

// Strip basic LaTeX text macros to give a human-readable caption.
function texToText(s) {
  if (!s) return "";
  let out = s;
  // Drop \label{...}
  out = out.replace(/\\label\{[^}]*\}/g, "");
  // Inline math $...$ → keep contents as-is, just drop the $
  out = out.replace(/\$([^$]+)\$/g, "$1");
  // \emph{x}, \textbf{x}, \textit{x}, \texttt{x} → x
  out = out.replace(/\\(?:emph|textbf|textit|texttt|textsc|mathbf|mathit)\{([^{}]*)\}/g, "$1");
  // \footnote{...} → drop entirely
  out = out.replace(/\\footnote\{[^{}]*\}/g, "");
  // \cite{key,key2}, \citep{...}, \citet{...} → [cite]
  out = out.replace(/\\(?:cite|citep|citet|citeauthor|citeyear)\*?\{[^}]*\}/g, "");
  // \ref{...}, \eqref{...} → ""
  out = out.replace(/\\(?:ref|eqref|autoref|Cref|cref|pageref|nameref)\{[^}]*\}/g, "");
  // Common math/macros
  out = out.replace(/\\fnl\b/g, "f_NL");
  out = out.replace(/\\BNL\b/g, "B_NL");
  out = out.replace(/\\Neff\b/g, "N_eff");
  out = out.replace(/\\sim\b/g, "~");
  out = out.replace(/\\approx\b/g, "≈");
  out = out.replace(/\\times\b/g, "×");
  out = out.replace(/\\sigma\b/g, "σ");
  out = out.replace(/\\alpha\b/g, "α");
  out = out.replace(/\\beta\b/g, "β");
  out = out.replace(/\\Lambda\b/g, "Λ");
  out = out.replace(/\\Delta\b/g, "Δ");
  out = out.replace(/\\ell\b/g, "ℓ");
  out = out.replace(/\\pm\b/g, "±");
  // Remaining \cmd{x} → x
  out = out.replace(/\\[A-Za-z]+\*?\{([^{}]*)\}/g, "$1");
  // \cmd → drop
  out = out.replace(/\\[A-Za-z]+\*?/g, "");
  // Escape chars
  out = out.replace(/\\\\/g, " ");
  // Drop residual TeX spacing commands like \! \, \; \: \> \quad
  out = out.replace(/\\[!,;:>]/g, "");
  out = out.replace(/\\(?:quad|qquad)\b/g, " ");
  out = out.replace(/[{}]/g, "");
  out = out.replace(/~/g, " ");
  // Whitespace
  out = out.replace(/\s+/g, " ").trim();
  return out;
}

// Truncate long captions for display.
function truncate(s, n = 280) {
  if (s.length <= n) return s;
  return s.slice(0, n - 1).trimEnd() + "…";
}

// Pull a short title from the caption (first sentence / clause, capped).
// Skip too-short heads (caption started with an unknown macro that
// stripped to nothing) and fall back to a fuller slice.
function captionTitle(caption) {
  const cleaned = caption.replace(/^\s+/, "");
  if (!cleaned) return "";
  const m = cleaned.match(/^([^.;:]+[.;:])/);
  let head = m ? m[1] : cleaned;
  head = head.replace(/[:;.]\s*$/, "").trim();
  // If the first clause is too short (e.g. caption started with "{Top:}"
  // or a one-word \BigAE-stripped label), fall back to the first 90 chars
  // of the full caption.
  if (head.length < 25) {
    head = truncate(cleaned, 110).replace(/[:;.]\s*$/, "");
  }
  return truncate(head, 110);
}

// Parse all \includegraphics + their nearest caption/label block from a .tex.
function extractFigures(texPath) {
  const src = readFileSync(texPath, "utf8");
  const out = [];
  // Walk the file looking for figure/figure* environments OR bare
  // \includegraphics; for each, find the nearest \caption{...} after it.
  const igRe = /\\includegraphics(?:\[[^\]]*\])?\{([^}]+)\}/g;
  let m;
  let ordinal = 0;
  while ((m = igRe.exec(src)) !== null) {
    ordinal++;
    const figFile = m[1].trim();
    const startIdx = m.index;
    // Search forward up to 8 KB for the next \caption{...}
    const window = src.slice(startIdx, startIdx + 8192);
    const capMatch = window.match(/\\caption(?:\[[^\]]*\])?\{/);
    let caption = "";
    let label = "";
    if (capMatch) {
      const capOpen = startIdx + capMatch.index + capMatch[0].length - 1;
      const balanced = readBalanced(src, capOpen);
      if (balanced) {
        const raw = balanced.content;
        // Extract \label{fig:...} from inside caption (or in the same window)
        const lbl = raw.match(/\\label\{([^}]*)\}/);
        if (lbl) label = lbl[1];
        caption = texToText(raw);
      }
    }
    // If no label inside caption, scan the surrounding 2KB before+after
    if (!label) {
      const broad = src.slice(Math.max(0, startIdx - 2048), startIdx + 4096);
      const lbl = broad.match(/\\label\{(fig:[^}]+)\}/);
      if (lbl) label = lbl[1];
    }
    out.push({ figFile, caption, label, ordinal });
  }
  return out;
}

// ──────────────────────────────────────────────────────────────────
// Asset resolution — try several public roots and image extensions.
// Returns { publicPath: "/images/foo.png" } or { missing: true, basename }.
// ──────────────────────────────────────────────────────────────────
function resolveAsset(figFile, publicRoots, extraSourceDirs = []) {
  // The .tex sometimes references "figures/foo.pdf" or just "foo.png".
  // Strip any directory prefix in the .tex reference and try multiple
  // extensions: .png preferred for web (browser-renderable), then .jpg.
  const cleanName = basename(figFile);
  const stem = cleanName.replace(/\.(pdf|png|jpg|jpeg)$/i, "");
  const tryExts = [".png", ".jpg", ".jpeg"];

  // 1) Look under each public root in priority order.
  for (const root of publicRoots) {
    const rootAbs = join(REPO, root);
    for (const ext of tryExts) {
      const candidate = join(rootAbs, stem + ext);
      if (existsSync(candidate)) {
        // Convert filesystem path to public URL.
        // Match either "public/" (repo-root canonical) or "site/public/"
        // (regenerated mirror). Both serve from "/" at runtime.
        const sitePublicIdx = candidate.indexOf("site/public/");
        if (sitePublicIdx >= 0) {
          return {
            publicPath: candidate.slice(sitePublicIdx + "site/public".length),
          };
        }
        const publicIdx = candidate.indexOf("/public/");
        if (publicIdx >= 0) {
          return {
            publicPath: candidate.slice(publicIdx + "/public".length),
          };
        }
        // Asset lives outside any public/ dir (e.g. pipelines/) — copy to
        // repo-root public/images/<stem>.png so it survives the prebuild
        // mirror into site/public/images.
        const target = join(REPO, CANONICAL_PUBLIC_IMAGES, stem + ext);
        try {
          mkdirSync(dirname(target), { recursive: true });
          copyFileSync(candidate, target);
          // Also mirror into site/public/images so dev server picks it up
          // before the next prebuild fires.
          const mirror = join(REPO, "site/public/images", stem + ext);
          mkdirSync(dirname(mirror), { recursive: true });
          copyFileSync(candidate, mirror);
          return {
            publicPath: "/images/" + stem + ext,
            copied: { from: candidate, to: target },
          };
        } catch (err) {
          console.warn(`  ⚠ copy failed for ${stem}${ext}:`, err.message);
        }
      }
    }
  }

  // 2) Probe extra source dirs (paper-local figures/, etc.) — copy to public.
  for (const root of extraSourceDirs) {
    const rootAbs = join(REPO, root);
    for (const ext of tryExts) {
      const candidate = join(rootAbs, stem + ext);
      if (existsSync(candidate)) {
        const target = join(REPO, CANONICAL_PUBLIC_IMAGES, stem + ext);
        try {
          mkdirSync(dirname(target), { recursive: true });
          copyFileSync(candidate, target);
          const mirror = join(REPO, "site/public/images", stem + ext);
          mkdirSync(dirname(mirror), { recursive: true });
          copyFileSync(candidate, mirror);
          return { publicPath: "/images/" + stem + ext };
        } catch (err) {
          console.warn(`  ⚠ copy failed for ${stem}${ext}:`, err.message);
        }
      }
    }
  }
  return { missing: true, basename: cleanName };
}

// Read current paperVersion from site/src/data/papers.ts (regex, not parse).
function loadPaperVersions() {
  const src = readFileSync(
    join(REPO, "site/src/data/papers.ts"),
    "utf8"
  );
  const versions = {};
  // Each paper entry: slug: "paper-XYZ", ... version: "vX.Y.Z",
  const re = /slug:\s*"([^"]+)"[\s\S]{0,400}?version:\s*"([^"]+)"/g;
  let m;
  while ((m = re.exec(src)) !== null) {
    versions[m[1]] = m[2];
  }
  return versions;
}

// ──────────────────────────────────────────────────────────────────
// Main
// ──────────────────────────────────────────────────────────────────
async function main() {
  const versions = loadPaperVersions();
  const missing = [];
  let totalUpserted = 0;
  const counts = {};

  for (const paper of PAPERS) {
    const texPath = join(REPO, paper.tex);
    if (!existsSync(texPath)) {
      console.warn(`✗ ${paper.label}: .tex not found at ${paper.tex}`);
      continue;
    }
    const figures = extractFigures(texPath);
    console.log(
      `\n${paper.label} (${paper.slug}) — ${figures.length} \\includegraphics ` +
      `in ${paper.tex}`
    );

    // Prune stale rows before re-seeding (figures removed from .tex disappear).
    const removed = await client.mutation(api.figures.removeByPaper, {
      paperSlug: paper.slug,
    });
    if (removed > 0) console.log(`  ↳ pruned ${removed} stale rows`);

    const version = versions[paper.slug] || "unknown";
    let kept = 0;
    for (const fig of figures) {
      const asset = resolveAsset(fig.figFile, paper.publicRoots);
      if (asset.missing) {
        missing.push({ paper: paper.slug, figure: fig.figFile });
        console.log(`  ⚠ missing on disk: ${fig.figFile}`);
        continue;
      }
      const title = captionTitle(fig.caption);
      const desc = truncate(fig.caption, 360);
      const alt = title || basename(fig.figFile);
      await client.mutation(api.figures.upsertByOrdinal, {
        paperSlug: paper.slug,
        ordinal: fig.ordinal,
        src: asset.publicPath,
        alt,
        title: title || `Figure ${fig.ordinal}`,
        desc,
        paperVersion: version,
        citationLabel: fig.label || undefined,
      });
      kept++;
      totalUpserted++;
    }
    counts[paper.slug] = kept;
    console.log(`  ✔ ${kept} figures upserted (version=${version})`);
  }

  console.log(`\n────────────────────────────`);
  console.log(`Total upserted: ${totalUpserted}`);
  for (const [slug, n] of Object.entries(counts)) {
    console.log(`  ${slug.padEnd(10)} ${n}`);
  }
  if (missing.length) {
    console.log(`\nMissing assets (${missing.length}) — flag in commit body:`);
    for (const m of missing) console.log(`  ${m.paper}  ${m.figure}`);
  }
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
