#!/usr/bin/env python3
"""Fail-closed P1B contracts learned from the v1B.0.109 exact-PDF board."""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any


SCHEMA = "bigbounce.p1b-science-contracts/v1"


def _require(condition: bool, message: str) -> None:
    if not condition:
        raise ValueError(message)


def _load_json(path: Path, label: str) -> dict[str, Any]:
    _require(path.is_file(), f"P1B {label} is missing: {path}")
    try:
        payload = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, UnicodeDecodeError, json.JSONDecodeError) as exc:
        raise ValueError(f"P1B {label} is invalid: {exc}") from exc
    _require(isinstance(payload, dict), f"P1B {label} must be a JSON object")
    return payload


def verify(root: Path, paths: dict[str, str]) -> dict[str, Any]:
    required = {
        "manuscript",
        "namaster_physical_spectrum_receipt",
        "bbn_execution_receipt",
        "s8_overlay_receipt",
        "analysis_manifest",
    }
    _require(set(paths) == required, "P1B science-contract path map differs")
    resolved = {key: root / value for key, value in paths.items()}
    manuscript = resolved["manuscript"].read_text(encoding="utf-8")

    namaster = _load_json(
        resolved["namaster_physical_spectrum_receipt"],
        "physical-spectrum receipt",
    )
    _require(namaster.get("status") == "PASS", "P1B physical-spectrum receipt is not PASS")
    _require(namaster.get("spectrum_convention") == "raw_C_ell", "P1B NaMaster spectrum must be raw C_ell")
    _require(namaster.get("ee_source") == "CAMB", "P1B EE spectrum must be generated by CAMB")
    _require(namaster.get("bb_source") == "CAMB_lensed", "P1B BB spectrum must be physical lensed CAMB")
    _require(namaster.get("production_realizations") == 500, "P1B physical production must contain 500 realizations")
    hashes = namaster.get("spectrum_sha256", {})
    _require(
        isinstance(hashes, dict)
        and set(hashes) == {"EE", "BB"}
        and all(isinstance(value, str) and len(value) == 64 for value in hashes.values()),
        "P1B physical EE/BB spectrum hashes are absent",
    )

    bbn = _load_json(resolved["bbn_execution_receipt"], "BBN execution receipt")
    _require(bbn.get("status") == "PASS", "P1B BBN execution receipt is not PASS")
    _require(bbn.get("camb_version") == "1.6.5", "P1B BBN receipt must bind CAMB 1.6.5")
    _require(
        isinstance(bbn.get("executed_table"), str) and bbn["executed_table"],
        "P1B executed BBN table is unnamed",
    )
    _require(
        isinstance(bbn.get("executed_table_sha256"), str)
        and len(bbn["executed_table_sha256"]) == 64,
        "P1B executed BBN table hash is absent",
    )
    _require(
        bbn.get("public_yaml_setting") == bbn.get("executed_table"),
        "P1B public YAML does not reproduce the executed BBN predictor",
    )

    s8 = _load_json(resolved["s8_overlay_receipt"], "S8 overlay receipt")
    _require(s8.get("status") == "PASS", "P1B S8 overlay receipt is not PASS")
    _require(s8.get("burn_in_fraction") == 0.30, "P1B S8 overlay must use 30 percent burn-in")
    _require(
        isinstance(s8.get("raw_samples"), int)
        and isinstance(s8.get("post_burn_samples"), int)
        and s8["raw_samples"] > s8["post_burn_samples"] > 0,
        "P1B S8 raw/post-burn sample counts are invalid",
    )

    manifest = _load_json(resolved["analysis_manifest"], "analysis manifest")
    paper_version = manifest.get("paper_version")
    _require(
        isinstance(paper_version, str) and paper_version in manuscript,
        "P1B analysis manifest version does not match the manuscript",
    )
    for forbidden in ("piles toward the upper edge", "data-driven pull to the edge"):
        _require(forbidden not in manuscript, f"P1B unsupported ALP prior-edge wording recurred: {forbidden}")
    _require(
        "full-$EB$" in manuscript or "full $EB$" in manuscript,
        "P1B full-EB likelihood limitation is absent",
    )

    return {
        "schema": SCHEMA,
        "verdict": "PASS",
        "contracts": {
            "namaster_raw_c_ell": True,
            "bbn_executed_provenance": True,
            "s8_uniform_burn_in": True,
            "alp_estimand_language": True,
            "version_matched_manifest": True,
        },
    }
