#!/usr/bin/env python3
"""Fail-closed P1B contracts learned from the v1B.0.109 exact-PDF board."""

from __future__ import annotations

import json
import re
import sys
import hashlib
from pathlib import Path
from typing import Any


SCHEMA = "bigbounce.p1b-science-contracts/v1"


def _require(condition: bool, message: str) -> None:
    if not condition:
        raise ValueError(message)


def _load_json(path: Path, label: str) -> dict[str, Any]:
    _require(path.is_file(), f"P1B {label} is missing: {path}")
    try:
        payload = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, UnicodeDecodeError, json.JSONDecodeError) as exc:
        raise ValueError(f"P1B {label} is invalid: {exc}") from exc
    _require(isinstance(payload, dict), f"P1B {label} must be a JSON object")
    return payload


def verify(root: Path, paths: dict[str, str]) -> dict[str, Any]:
    required = {
        "manuscript",
        "namaster_summary",
        "namaster_c10_receipt",
        "namaster_declared_receipt",
        "bbn_execution_receipt",
        "s8_overlay_receipt",
        "analysis_manifest",
    }
    _require(set(paths) == required, "P1B science-contract path map differs")
    resolved = {key: root / value for key, value in paths.items()}
    manuscript = resolved["manuscript"].read_text(encoding="utf-8")

    namaster = _load_json(resolved["namaster_summary"], "physical-spectrum summary")
    _require(namaster.get("run_mode") == "production", "P1B NaMaster result is not a production run")
    _require(namaster.get("n_mc_realizations") == 500, "P1B physical production must contain 500 realizations")
    spectra = namaster.get("physical_spectra", {})
    contract = spectra.get("contract", {})
    _require(contract.get("raw_cl") is True, "P1B NaMaster spectrum must be raw C_ell")
    _require(spectra.get("generator") == "CAMB", "P1B EE/BB spectra must be generated by CAMB")
    _require(
        spectra.get("resolved_camb_version") == spectra.get("expected_camb_version")
        and spectra.get("production_version_match") is True,
        "P1B NaMaster production CAMB version is not pinned",
    )
    hashes = spectra.get("sha256", {})
    _require(
        isinstance(hashes, dict)
        and set(hashes) == {"cl_ee_raw_uK2", "cl_bb_raw_uK2"}
        and all(isinstance(value, str) and len(value) == 64 for value in hashes.values()),
        "P1B physical EE/BB spectrum hashes are absent",
    )
    validation = spectra.get("validation", {})
    _require(
        validation.get("status") == "pass"
        and 0 < validation.get("raw_cl_ee_at_ell_check_uK2", 1) < 0.05,
        "P1B raw-C_ell scale validation failed",
    )
    _require(
        namaster.get("window_equivalence_max_abs", 1) <= 1e-10,
        "P1B exact window-equivalence tolerance failed",
    )
    expected_suites = {
        "namaster_c10_receipt": "c10_merged",
        "namaster_declared_receipt": "declared_fsky_sign_merged",
    }
    for key, suite in expected_suites.items():
        receipt = _load_json(resolved[key], key.replace("_", " "))
        _require(receipt.get("suite") == suite, f"P1B {key} suite mismatch")
        _require(receipt.get("n_real") == 500, f"P1B {key} does not bind 500 realizations")
        _require(
            receipt.get("seed_start") == 42
            and receipt.get("seed_end") == 541
            and isinstance(receipt.get("result_sha256"), str)
            and len(receipt["result_sha256"]) == 64,
            f"P1B {key} seed/hash contract failed",
        )

    bbn = _load_json(resolved["bbn_execution_receipt"], "BBN execution receipt")
    _require(bbn.get("status") == "PASS", "P1B BBN execution receipt is not PASS")
    _require(bbn.get("camb_version") == "1.6.5", "P1B BBN receipt must bind CAMB 1.6.5")
    _require(
        bbn.get("executed_table") == "PRIMAT_Yp_DH_ErrorMC_2021.dat",
        "P1B executed BBN table is not the frozen CAMB 1.6.5 default",
    )
    _require(
        isinstance(bbn.get("executed_table_sha256"), str)
        and len(bbn["executed_table_sha256"]) == 64,
        "P1B executed BBN table hash is absent",
    )
    _require(
        bbn.get("public_yaml_setting") == bbn.get("executed_table"),
        "P1B public YAML does not reproduce the executed BBN predictor",
    )
    configs = bbn.get("validated_configs")
    _require(
        isinstance(configs, list) and len(configs) == 4,
        "P1B BBN receipt must bind all four public reproduction YAMLs",
    )
    for config in configs:
        _require(isinstance(config, dict), "P1B BBN config receipt is malformed")
        config_path = root / str(config.get("path", ""))
        _require(config_path.is_file(), f"P1B BBN config is missing: {config_path}")
        _require(
            hashlib.sha256(config_path.read_bytes()).hexdigest()
            == config.get("sha256"),
            f"P1B BBN config hash mismatch: {config_path}",
        )
        _require(
            config.get("bbn_predictor") == bbn.get("executed_table"),
            f"P1B BBN config predictor mismatch: {config_path}",
        )

    s8 = _load_json(resolved["s8_overlay_receipt"], "S8 overlay receipt")
    _require(s8.get("status") == "PASS", "P1B S8 overlay receipt is not PASS")
    _require(s8.get("burn_in_fraction") == 0.30, "P1B S8 overlay must use 30 percent burn-in")
    _require(
        isinstance(s8.get("raw_samples"), int)
        and isinstance(s8.get("post_burn_samples"), int)
        and s8["raw_samples"] > s8["post_burn_samples"] > 0,
        "P1B S8 raw/post-burn sample counts are invalid",
    )
    result_path = resolved["s8_overlay_receipt"].with_name(
        s8.get("result_file", "")
    )
    _require(result_path.is_file(), "P1B S8 result bound by the receipt is missing")
    _require(
        hashlib.sha256(result_path.read_bytes()).hexdigest()
        == s8.get("result_sha256"),
        "P1B S8 result hash does not match its receipt",
    )

    manifest = _load_json(resolved["analysis_manifest"], "analysis manifest")
    paper_version = manifest.get("paper_version")
    version_match = re.search(
        r"\\newcommand\{\\paperVersion\}\{([^}]+)\}", manuscript
    )
    _require(version_match is not None, "P1B manuscript paperVersion macro is absent")
    _require(
        isinstance(paper_version, str) and paper_version == version_match.group(1),
        "P1B analysis manifest version does not match the manuscript",
    )
    for forbidden in ("piles toward the upper edge", "data-driven pull to the edge"):
        _require(forbidden not in manuscript, f"P1B unsupported ALP prior-edge wording recurred: {forbidden}")
    _require(
        "full-$EB$" in manuscript or "full $EB$" in manuscript,
        "P1B full-EB likelihood limitation is absent",
    )

    return {
        "schema": SCHEMA,
        "verdict": "PASS",
        "contracts": {
            "namaster_raw_c_ell_500mc": True,
            "bbn_executed_provenance": True,
            "s8_uniform_burn_in": True,
            "alp_estimand_language": True,
            "version_matched_manifest": True,
        },
    }


def main() -> int:
    """Verify the repository-configured contract instead of silently doing nothing."""
    root = Path(__file__).resolve().parents[1]
    rules = _load_json(root / "project-context/pre-review-rules.json", "pre-review rules")
    paths = rules.get("p1b_science_contract_paths")
    if not isinstance(paths, dict):
        raise ValueError("P1B science-contract path map is absent from pre-review rules")
    result = verify(root, paths)
    print(json.dumps(result, indent=2, sort_keys=True))
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except (OSError, ValueError) as exc:
        print(f"FAIL: {exc}", file=sys.stderr)
        raise SystemExit(1)
